:::{#def-deviation-subpop-mean}
#### Deviation of an observation from its subpopulation mean

The **deviation of an observation from its subpopulation mean**
in a probabilistic model $p(Y \mid X)$,
is the difference between an observed value
and its model-implied mean given covariates:

$$\devn(y_i) \eqdef y_i - \E{Y_i \mid X_i}$$ {#eq-def-deviation-subpop-mean}
:::

:::{.notes}
Many sources call deviations "error" or "noise."
The model-implied mean
can be viewed as an estimate of $Y_i$,
before $y_i$ is observed.
However, an estimation error is defined as an estimate minus its estimand
(see [estimation error](estimation.qmd#def-estimation-error)),
and deviation is the observed value minus its estimand,
so the deviation is actually the *negative* of the estimation error of the mean $\E{Y_i \mid X_i}$
with respect to its estimand $Y_i$:

$$\devn(y_i) = -(\erf{$\E{Y_i \mid X_i}$})$$

On the other hand,
each observation $y_i$ can be viewed
as an estimate of $\E{Y_i \mid X_i}$
(albeit an imprecise one, individually, since $n=1$),
so the deviation can be interpreted as the estimation error of $y_i$ 
with respect to $\E{Y_i \mid X_i}$:

$$\devn(y_i) = \erf{y_i}$$
:::

---

We can rearrange @eq-def-deviation-subpop-mean
to view $y_i$ as
the sum of its mean plus the deviation
(often called error/noise):

$$y_i = \E{Y_i \mid X_i} + \devn(y_i)$$
