{{< include macros.qmd >}}

:::{#exr-logistic-coef-interp}

For @eq-wcgs-model-1,
derive interpretations of $\beta_0$, $\beta_P$, $\beta_A$, and $\beta_{PA}$ 
on the odds **and** log-odds scales, 
State the interpretations concisely in math **and** in words.

:::

---

:::{#sol-logistic-coef-interp}

\ 

```{r}
# include: false
age_offset = 0L
```

$$
\ba
\eta(P=0,A=0) &= \beta_0 + \beta_P 0 + \beta_A 0
\\
&= \beta_0 + 0 + 0
\\
&= \beta_0
\ea
$$

Therefore:

$$\beta_{0} = \logitf{P(Y=1|P=0,A=0)}$${#eq-wcgs-intxn-beta0}

$\beta_{0}$ is the natural logarithm of the odds ("log-odds") of experiencing CHD for a `r age_offset` year-old person with a type B personality; that is,

---

$\text{e}^{\beta_{0}}$ is the odds of experiencing CHD 
for a `r age_offset` year-old with a type B personality,

$$
\begin{aligned}
\expf{\beta_{0}}
&= \frac{\Pr(Y= 1| P = 0, A = 0)}{1-\Pr(Y= 1| P = 0, A = 0)} \\
&= \frac
{\Pr(Y= 1| P = 0, A = 0)}
{\Pr(Y= 0| P = 0, A = 0)}
\end{aligned}
$$

---

$$
\ba
\deriv{a}\eta(P=0, A = a) 
&= \deriv{a} (\beta_0 + \beta_P 0 + \beta_A a + \beta_{PA}(0\cdot a))
\\
&= \deriv{a}\beta_0 + \deriv{a}\beta_P 0 + \deriv{a}\beta_A a + \deriv{a}\beta_{PA}(0\cdot a))
\\
&=  0 + 0 + \beta_A + 0
\\
&= \beta_A
\ea
$$

Therefore:

$$\beta_A = \deriv{a}\eta(P=0, A = a)$${#eq-wcgs-intxn-betaA}

$\beta_A$ is the slope of the log-odds of CHD with respect to age, for individuals with personality type B.

Alternatively:

$$
\begin{aligned}
\beta_{A}
&= \eta(P = 0, A = a + 1)- \eta(P = 0, A = a)
\end{aligned}
$$

That is,
$\beta_{A}$ is the difference in 
log-odds of experiencing CHD experiencing CHD 
per one-year difference in age 
between two individuals with type B personalities.

---

$$
\ba
\expf{\beta_{A}} &= \expf{\eta(P = 0, A = a + 1)- \eta(P = 0, A = a)}
\\
&= \frac{\expf{\eta(P = 0, A = a + 1)}}{\expf{\eta(P = 0, A = a)}}
\\
&= \frac{\omega(P = 0, A = a + 1)}{\omega(P = 0, A = a)}
\\
&= \frac
{\oddst(Y= 1|P=0, A = a + 1)}
{\oddst(Y= 1|P=0, A = a)}
\\
&= \theta(\Delta a = 1 | P = 0)
\ea
$$

* The odds ratio of experiencing CHD (aka "the odds ratio") 
differs by a factor of $\text{e}^{\beta_{A}}$ 
per one-year difference in age 
between individuals with type B personality.

---

$\beta_{P}$ is the difference in log-odds of experiencing CHD
for a `r age_offset` year-old person with type A personality
compared to a `r age_offset` year-old person with type B personality;
that is,

$$\b_P = \eta(P = 1, A = 0) - \eta(P=0, A = 0)$${#eq-wcgs-intxn-betaP}

---

-   $\text{e}^{\beta_{P}}$ is the ratio of the odds (aka "the odds ratio")
    of experiencing CHD, 
    for a `r age_offset`-year old individual with type A personality 
    vs a `r age_offset`-year old individual with type B personality; that is,

$$
\expf{\beta_{P}}
= \frac
{\oddst(Y= 1|P=1, A = 0)}
{\oddst(Y= 1|P=0, A = 0)}
$$

---

$$
\ba
\deriv{a}\eta(P=\red{1}, A = a) &= \red{\beta_A + \beta_{PA}}
\\
\deriv{a}\eta(P=\blue{0}, A = a) &= \blue{\beta_A}
\ea
$$

Therefore:

$$
\ba
\deriv{a}\eta(P=\red{1}, A = a) - \deriv{a}\eta(P=\blue{0}, A = a) &= \red{\beta_A + \beta_{PA}} - \blue{\beta_A}
\\
&= \beta_{PA}
\ea
$$

That is,

$$
\ba
\beta_{PA} &= \deriv{a}\eta(P=\red{1}, A = a) - \deriv{a}\eta(P=\blue{0}, A = a)
\\
&= \deriv{a}\eta(P=\red{1}, A = a) - \deriv{a}\eta(P=\blue{0}, A = a)
\ea
$$

$\beta_{PA}$ is the difference in
the slopes of log-odds over age between
participants with Type A personalities and
participants with Type B personalities.

---

Accordingly, 
the odds ratio of experiencing CHD per one-year difference in age
differs by a factor of $\text{e}^{\beta_{PA}}$
for participants with type A personality compared to
participants with type B personality; that is,

$$
\ba
\theta(\Delta a = 1 | P = 1)
= \expf{\beta_{PA}} \times \theta(\Delta a = 1 | P = 0)
\ea
$$

or equivalently:

$$
\expf{\beta_{PA}} = 
\frac
{\theta(\Delta a = 1 | P = 1)}
{\theta(\Delta a = 1 | P = 0)}
$$

:::
