project:
  type: website
  output-dir: _site
  render:
    # Only render the files that were in the original book
    - index.qmd
    - Intro-to-GLMs.qmd
    - glms.qmd
    - Linear-models-overview.qmd
    - logistic-regression.qmd
    - count-regression.qmd
    - intro-multilevel-models.qmd
    - time-to-event-models.qmd
    - intro-to-survival-analysis.qmd
    - proportional-hazards-models.qmd
    - parametric-survival-models.qmd
    - top-ten-concepts.qmd
    - appendices-are-prereqs.qmd
    - math-prereqs.qmd
    - data.qmd
    - exploratory-descriptive.qmd
    - probability.qmd
    - basic-statistical-methods.qmd
    - classification.qmd
    - estimation.qmd
    - inference.qmd
    - intro-MLEs.qmd
    - intro-bayes.qmd
    - common-mistakes.qmd
    - notation.qmd
    - intro-to-R.qmd
    - CONTRIBUTING.qmd
    - exam-formula-sheet.qmd
    - practice-exam-mle-linreg.qmd
    - package-versions.qmd

website:
  title: "Regression Models for Epidemiology"
  site-url: https://d-morrison.github.io/rme/
  description: "Lecture notes for Epidemiology 204: Quantitative Epidemiology III (Statistical Models)"
  page-footer:
    left:
      - text: "Copyright 2024-2026, Douglas Ezra Morrison"
  back-to-top-navigation: true
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/d-morrison/rme
  repo-actions: [edit, issue, source]
  google-analytics: "G-VS314RJ2KP"
  navbar:
    right:
      - icon: github
        href: https://github.com/d-morrison/rme
        aria-label: GitHub
    left:
      - text: "Home"
        href: index.qmd
      - text: "Chapters"
        menu:
          - text: "Introduction to GLMs"
            href: Intro-to-GLMs.qmd
          - text: "---"
          - text: "Generalized Linear Models"
            href: glms.qmd
          - text: "Linear Models Overview"
            href: Linear-models-overview.qmd
          - text: "Logistic Regression"
            href: logistic-regression.qmd
          - text: "Count Regression"
            href: count-regression.qmd
          - text: "Multilevel Models"
            href: intro-multilevel-models.qmd
          - text: "---"
          - text: "Time to Event Models"
            href: time-to-event-models.qmd
          - text: "Introduction to Survival Analysis"
            href: intro-to-survival-analysis.qmd
          - text: "Proportional Hazards Models"
            href: proportional-hazards-models.qmd
          - text: "Parametric Survival Models"
            href: parametric-survival-models.qmd
          - text: "---"
          - text: "Top Ten Concepts"
            href: top-ten-concepts.qmd
      - text: "Appendices"
        menu:
          - text: "Math Prerequisites"
            href: math-prereqs.qmd
          - text: "Data"
            href: data.qmd
          - text: "Exploratory and Descriptive Methods"
            href: exploratory-descriptive.qmd
          - text: "Probability"
            href: probability.qmd
          - text: "Basic Statistical Methods"
            href: basic-statistical-methods.qmd
          - text: "Classification"
            href: classification.qmd
          - text: "Estimation"
            href: estimation.qmd
          - text: "Inference"
            href: inference.qmd
          - text: "Introduction to MLEs"
            href: intro-MLEs.qmd
          - text: "Introduction to Bayesian Statistics"
            href: intro-bayes.qmd
          - text: "Common Mistakes"
            href: common-mistakes.qmd
          - text: "Notation"
            href: notation.qmd
          - text: "Introduction to R"
            href: intro-to-R.qmd
          - text: "Exam Formula Sheet"
            href: exam-formula-sheet.qmd
          - text: "Practice Exam: MLEs and Linear Regression"
            href: practice-exam-mle-linreg.qmd
          - text: "Package Versions"
            href: package-versions.qmd

bibliography: references.bib

callouty-theorem:
  thm:
    override-title: false # do not have the filter set
                          # or override a callout title
    callout: # parameters of the wrapping callout
             # see Quarto callout docs for details
      type: note
      appearance: minimal
  prp:
    override-title: false
    callout:
      type: note
      appearance: minimal
  exr:
    override-title: false
    callout:
      type: tip
      appearance: minimal
  proof: # also support wrapping proof-like environments
    override-title: true # override the callout title with
                         # the proof-type label,
                         # appending the element name when provided
    callout:
      type: note
      appearance: default
      collapse: true
      icon: true
  solution:
    override-title: true
    callout:
      type: note
      appearance: default
      collapse: true
      icon: true
  remark:
    override-title: true
    callout:
      type: tip
      appearance: default
      collapse: false
      icon: true

format:
  html:
    filters:
      - callouty-theorem
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: true
    code-tools: true
    code-link: true
    code-summary: "Show R code"
    highlight-style: arrow
    lightbox: true
    link-external-icon: true
    embed-resources: false
    fig-cap-location: top
    html-math-method: mathjax
    number-sections: true
    number-depth: 3
    df-print: paged
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (z)"
    subject: "Epidemiology 204"
  revealjs:
    filters:
      - filters/revealjs-slidebreak-after-h1.lua
    search: false
    lightbox: true
    theme: dark
    embed-resources: false
    fig-cap-location: top
    html-math-method: mathjax
    smaller: true
    number-sections: true
    progress: true
    incremental: false
    df-print: paged
    number-depth: 2
    slide-number: true
    shift-heading-level-by: 0
    slide-level: 2
    scrollable: true
    echo: true
    margin: 0.0
    code-fold: true
    code-link: true
    code-summary: "[R code]"
    auto-stretch: true
    fig-height: 5
    fig-width: 7
  pdf:
    filters:
      - callouty-theorem
    geometry:
      - top=15mm
      - bottom=20mm
    keep-md: false
    keep-tex: false
    toc: true
    fig-pos: "H"
    toc-title: Contents
    df-print: tibble
    links-as-notes: true
    documentclass: article
    colorlinks: true
    number-sections: true
    number-depth: 3
    include-in-header:
      text: |
        \newcounter{chapter}
        \renewcommand{\thechapter}{\arabic{section}}
        \usepackage{etoolbox}
        \makeatletter
        \AtBeginDocument{%
          \let\quarto@cl@chapter\cl@chapter
          \appto\cl@section{\quarto@cl@chapter}}
        \makeatother
  docx:
    filters:
      - callouty-theorem
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    df-print: tibble
    prefer-html: true
crossref:
  chapters: false
comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true
