{{< include latex-macros/macros.qmd >}}

::: {#exr-prob-to-odds}
Find a general formula for converting probabilities into odds.
:::

---

:::{#sol-prob-to-odds}

Using @def-odds and @cor-p-neg:

$$
\ba
\odds &\eqdef \frac{\Pr(A)}{\Pr(\neg A)}
\\ &= \frac{\pi}{1-\pi}
\ea
$$

:::

---

:::{#thm-prob-to-odds}
If $\prob$ is the probability of an event $A$
and $\odds$ is the corresponding odds of $A$,
then:

$$\odds = \frac{\prob}{1-\prob}$${#eq-odds-prob}

:::

::: proof
By @sol-prob-to-odds.
:::

---

::: notes
The mathematical relationship between odds $\odds$ and probabilities $\pi$, 
which is represented in @eq-odds-prob,
is a core component of logistic regression models,
as we will see in the rest of this chapter.
Let's give the expression on the righthand side of @eq-odds-prob
its own name and symbol,
so that we can refer to it concisely:
:::

:::{#def-odds-fn}
#### Odds function

The **odds function** is defined as:
$$\oddsf{\pi} \eqdef \frac{\pi}{1-\pi}$$ {#eq-def-odds-fn}

:::

---

::: notes
We can use the odds function (@def-odds-fn) 
to simplify @eq-odds-prob (in @thm-prob-to-odds)
into a more concise expression,
which is easier to remember and manipulate:
:::

:::{#cor-oddsf-to-odds}
If $\prob$ is the probability of an outcome $A$
and $\odds$ is the corresponding odds of $A$,
then:

$$\odds = \oddsf{\prob}$${#eq-odds-odds-fn}

:::

::: notes
In other words,
the odds function rescales probabilities into odds. 
:::

---

::: proof

By @thm-prob-to-odds and @def-odds-fn.

:::

---

:::{#exr-graph-odds-fn}
Graph the odds function.
:::

---

:::{#sol-graph-odds-fn}

::: notes
@fig-odds-probs graphs the odds function.
:::

```{r}
#| code-fold: true
#| label: fig-odds-probs
#| fig-cap: "Odds versus probability"

odds <- function(pi) pi / (1 - pi)
library(ggplot2)
ggplot() +
  geom_function(
    fun = odds,
    arrow = arrow(ends = "last"),
    mapping = aes(col = "odds function")
  ) +
  xlim(0, .99) +
  xlab("Probability") +
  ylab("Odds") +
  geom_abline(aes(
    intercept = 0,
    slope = 1,
    col = "y=x"
  )) +
  theme_bw() +
  labs(colour = "") +
  theme(legend.position = "bottom")
```

:::
