{{< include latex-macros/macros.qmd >}}

:::{#def-cond-hazard}
#### conditional hazard

The **conditional hazard** of outcome $T$ at value $t$,
given covariate vector $\vx$,
is the conditional density of the event $T=t$,
given $T \ge t$ and $\vX = \vx$:

{{< include _eq-def-cond-haz.qmd >}}

:::

---

:::{#def-base-hazard}

#### baseline hazard

:::: notes
The **baseline hazard**, **base hazard**, or **reference hazard**,
denoted $\haz_0(t)$ or $\lambda_0(t)$,
is the [hazard function](intro-to-survival-analysis.qmd#def-hazard)
for the subpopulation of individuals
whose covariates are all equal to their reference levels:

::::

{{< include _eq-def-baseline-haz.qmd >}}

:::

::: notes
The baseline hazard is *somewhat* analogous to
the intercept term in linear regression,
but it is **not** a mean.
:::

---

::: notes
Similarly:
:::

{{< include _def-base-cuhaz.qmd >}}

---

::: notes
Also:
:::

:::{#def-baseline-surv}
#### Baseline survival function

The **baseline survival function**
is the survival function
for an individual whose covariates
are all equal to their default values.

$$\surv_0(t) \eqdef \surv(t | \vX = \vzero)$$
:::

---

::: notes
Now, let's define ***how*** the hazard function depends on covariates.
We typically use a log link to model the relationship between
the hazard function, $\haz(t|\vx)$, and
the linear component, $\eta(t|\vx)$,
as we did for Poisson models in @sec-count-reg;
that is:

:::

{{< include _def-loghaz.qmd >}}

---

{{< include _def_cond-loghaz.qmd >}}

::: note
In contrast with Poisson regression,
here $\loghaz(t|\vx)$ depends on **both** $t$ **and** $\vx$.
:::

---

{{< include _def-base-loghaz.qmd >}}

---

:::{#thm-haz-from-loghaz}
$$
\begin{aligned}
\haz(t|\vx) &= \exp{\loghaz(t|\vx)}
\ea
$$
:::

---

{{< include _def-diffloghaz.qmd >}}

---

{{< include _thm-diff-loghaz.qmd >}}

---

{{< include _cor-hazard-ratio-diffloghaz.qmd >}}

---

{{< include _def-difflog-hazard-from-baseline.qmd >}}


---

{{< include _thm-loghaz-decomp.qmd >}}

---

{{< include _def-hr-vs-baseline.qmd >}}

---

{{< include _cor-hazard-ratio-vs-baseline.qmd >}}

---

:::{#cor-difflogodds-log-HR}

$$\diffloghaz(t|\vx) = \logf{\theta(t| \vx)}$$

:::
