{{< include latex-macros/macros.qmd >}}

::: notes

Now that we have defined odds, we can introduce another way of comparing event probabilities: odds ratios.

:::

---

{{< include _def_OR.qmd >}}

---

There's a 1:1 mapping between probability and odds, 
and according to that mapping, 
the odds are equal between two covariate patterns 
IF and ONLY IF the probabilities are also equal between those patterns. 
So, 
testing whether an odds ratio = 1 is equivalent to 
testing whether the corresponding risk ratio = 1, 
and also equivalent to 
testing whether the risk difference = 0.
Therefore, 
in **hypothesis testing**, 
if the null hypothesis is no effect, 
then we can shift between RD, RR, and OR.
But when we're talking about **point estimates** and **CIs**, 
we need to limit our conclusions to the effect measure(s) that we actually estimated, 
because the *sizes* of RDs, RRs, and ORs don't have a simple relationship to each other, 
except when pi_1=pi_2 (as shown by @fig-rd-rr-or). 

---

{{< include _sec_OR-ratio-ratio.qmd >}}

---

{{< include _exm-OR.qmd >}}

---

#### A shortcut for calculating odds ratio estimates {.smaller}

{{< include _sec-2x2-OR-shortcut.qmd >}}

---

#### Properties of odds ratios {#sec-OR-props}

{{< include _sec_ORs_reversible.qmd >}}

---

#### Odds Ratios vs Probability (Risk) Ratios {#sec-OR-RR}

{{< include _sec_OR-RR.qmd >}}

---

#### Odds Ratios in Case-Control Studies {#sec-CC-studies}

{{< include _sec_ORs-in-case-control_studies.qmd >}}

---

#### Odds Ratios in Cross-Sectional Studies

{{< include _sec_ORs-in-cross-sectional-studies.qmd >}}
