
---

::: notes
How do we fit a proportional hazards regression model? We need to
estimate the coefficients of the covariates, and we need to estimate the
base hazard $h_0(t)$. For the covariates, supposing for simplicity that
there are no tied event times, let the event times for the whole data
set be $t_1, t_2,\ldots,t_D$. Let the risk set at time $t_i$ be $R(t_i)$
and
:::

$$
\begin{aligned}
\eta(\boldsymbol{x}) &= \beta_1x_{1}+\cdots+\beta_p x_{p}\\
\theta(\boldsymbol{x}) &= e^{\eta(\boldsymbol{x})}\\
h(t|X=x)&= h_0(t)e^{\eta(\boldsymbol{x})}=\theta(\boldsymbol{x}) h_0(t)
\end{aligned}
$$

---

::: notes
Conditional on a single failure at time $t$, the probability that the
event is due to subject $f\in R(t)$ is approximately
:::

$$
\begin{aligned}
\Pr(f \text{ fails}|\text{1 failure at } t)
&= \frac{h_0(t)e^{\eta(\boldsymbol{x}_f)}}{\sum_{k \in R(t)}h_0(t)e^{\eta(\boldsymbol{x}_f)}}\\
&=\frac{\theta(\boldsymbol{x}_f)}{\sum_{k \in R(t)} \theta(\boldsymbol{x}_k)}
\end{aligned}
$$

::: notes
The logic behind this has several steps.
We first fix (ex post) the failure times
and note that in this discrete context,
the probability $p_j$ that a subject $j$ in the risk set fails at time $t$
is just the hazard of that subject at that time.
:::

If all of the $p_j$ are small,
the chance that exactly one subject fails
is


$$
\sum_{k\in R(t)}p_k\left[\prod_{m\in R(t), m\ne k} (1-p_m)\right]\approx\sum_{k\in R(t)}p_k
$$

---

::: notes
If subject $i$ is the one who experiences the event of interest at time
$t_i$,
then the **partial likelihood** is
:::

$$
\Lik^*(\beta|T)=
\prod_i \frac{\theta(x_i)}{\sum_{k \in R(t_i)} \theta(\boldsymbol{x}_k)}
$$

::: notes
and we can numerically maximize this with respect to the coefficients
$\boldsymbol{\beta}$ that specify
$\eta(\boldsymbol{x}) = \boldsymbol{x}'\boldsymbol{\beta}$.
When there are tied event times adjustments need to be made,
but the likelihood is still similar.
Note that we don't need to know the base hazard to solve
for the coefficients.

Once we have coefficient estimates
$\hat{\boldsymbol{\beta}} =(\hat \beta_1,\ldots,\hat\beta_p)$,
this also defines $\hat\eta(x)$ and $\hat\theta(x)$,
and then the estimated base cumulative hazard function is $$\hat H(t)=
\sum_{t_i < t} \frac{d_i}{\sum_{k\in R(t_i)} \theta(x_k)}$$,
which reduces to the Nelson-Aalen estimate when there are no covariates.
There are numerous other estimates that have been proposed as well.
:::
