{{< include macros.qmd >}}

::: notes
In logistic regression, we will make use of a mathematically-convenient transformation of probability, called *odds*:
:::

{{< include _def-odds.qmd >}}

---

{{< include _def_conditional_odds.qmd >}}

---

{{< include _exm-odds.qmd >}}

---

{{< include _exr-odds.qmd >}}

---

{{< include _sec_odds_fn.qmd >}}

---

:::{#thm-est-odds}
#### One-sample MLE for odds

Let $X_1,...X_n$ be a set of $n$ $\iid$ Bernoulli trials, and let $X = \sumin X_i$ be their sum.

Then the maximum likelihood estimate of the odds of $X=1$, $\odds$, is:

$$
\hat{\odds}= \frac{x}{n-x}
$$

:::

---

::: proof

$$
\begin{aligned}
1-\hat\pi
&= 1-\frac{x}{n}\\
&= \frac{n}{n} - \frac{x}{n}\\
&= \frac{n - x}{n}
\end{aligned}
$$

Thus, the estimated odds is:

$$
\begin{aligned}
\frac{\hat\pi}{1-\hat\pi}
&= \frac{\left(\frac{x}{n}\right)}{\left(\frac{n-x}{n}\right)}\\
&= \frac{x}{n-x}
\end{aligned}
$$

:::: notes
That is, odds can be calculated directly as "# events" divided by "# nonevents" (without needing to calculate $\hat\pi$ and $1-\hat\pi$ first).
::::

:::

---

::::{#exm-odds-shortcut}

#### Calculating odds using the shortcut
In @exm-odds, we calculated
$$
\begin{aligned}
\odds(OC)
&=`r (13/5000)/(1- (13/5000))`
\end{aligned}
$$

Let's recalculate this result using our shortcut.

::::

---

::::{#sol-odds-shortcut}
$$
\begin{aligned}
\odds(OC)
&=\frac{13}{5000-13}\\
&=`r (13)/(5000- 13)`
\end{aligned}
$$

Same answer as in @exm-odds!

::::

---

:::{#thm-odds-simplified}

#### Simplified expressions for odds function

::: notes
Two equivalent expressions for the odds function are:
:::

$$
\ba
\oddsf{\pi} &= \frac{1}{\pi^{-1}-1}
\\ &= \invf{\pi^{-1}-1}
\ea
$$ {#eq-odds-reduced}

:::

---

:::{#exr-odds2}
Prove @thm-odds-simplified.
:::

---

:::{#sol-odds2}
Starting from @def-odds-fn:

$$
\ba
\oddsf{\pi} &= \frac{\pi}{1-\pi}
\\
&= \frac{\pi}{1-\pi}\frac{\pi^{-1}}{\pi^{-1}}
\\
&= \frac{\pi\pi^{-1}}{(1-\pi)\pi^{-1}}
\\
&= \frac{1}{(\pi^{-1}-\pi\pi^{-1})}
\\
&= \frac{1}{(\pi^{-1}-1)}
\\
&= \invf{\pi^{-1}-1}
\ea
$$

:::

---

#### Odds of rare events

For rare events (small $\pi$), odds and probabilities are nearly equal, because $1-\pi \approx 1$ (see @fig-odds-probs).

For example, in @exm-odds, the probability and odds differ by $`r abs(pi_OC - odds_OC)`$.

---

:::{#exr-odds-probs}

What odds value corresponds to the probability $\pi = 0.2$, and what is the numerical difference between these two values?

:::

---

::::{.solution}
$$
\odds = \frac{\pi}{1-\pi}
=\frac{.2}{.8}
= .25
$$
::::

---

:::{#thm-odds-minus-probs}

Let $\odds = \frac{\pi}{1-\pi}$. Then:

$$\odds - \pi =  \odds \cd \pi$$

:::

---

:::{#exr-odds-minus-probs}

Prove @thm-odds-minus-probs.

:::

---

::: solution

$$
\ba
\odds - \pi
&= \frac{\pi}{1-\pi} - \pi
\\ &= \frac{\pi}{1-\pi} - \frac{\pi(1-\pi)}{1-\pi}
\\ &= \frac{\pi}{1-\pi} - \frac{\pi - \pi^2}{1-\pi}
\\ &= \frac{\pi - (\pi - \pi^2)}{1-\pi}
\\ &= \frac{\pi - \pi + \pi^2}{1-\pi}
\\ &= \frac{\pi^2}{1-\pi}
\\ &= \frac{\pi}{1-\pi} \pi
\\ &= \odds \pi
\ea
$$

:::

---

:::{#lem-odds-neg}
#### Odds of a non-event

If $\pi$ is the odds of event $A$
and $\odds$ is the corresponding odds of $A$,
then the odds of $\neg A$ are:

$$
\ba
\odds(\neg A) &= \frac{1-\pi}{\pi}
\\&= \pi^{-1}-1
\ea
$$

:::

::: proof
Left to the reader.
:::

---

