{{< include macros.qmd >}}

:::{#exr-ci-OR}
Given
a maximum likelihood estimate $\hb$
and
a corresponding estimated covariance matrix 
$\hS \eqdef \widehat{\Covt}(\hb)$, 
calculate a 95% confidence interval for the odds ratio 
comparing covariate patterns $\vx$ and $\vxs$, $\ror(\vx,\vxs)$.
:::

---

:::{#sol-ci-OR}

::: notes
By @thm-dist-mle,
a 95% confidence interval for $\ror(\vx,\vxs)$
can be constructed as:

$$\hat\ror \pm 1.96 * \HSE{\hat\ror}$${#eq-ci-OR-direct}
However, $\HSE{\hat\ror}$ seems difficult to compute;
doing so would require using the 
[delta method](https://en.wikipedia.org/wiki/Delta_method).

Instead, using the invariance property of MLEs,
we can first calculate a confidence interval for the log of the odds ratio,
$\logf{\ror(\vx,\vxs)} \in (L,R)$,
and then exponentiate the endpoints of that log-odds-scale confidence interval:
:::

$$\ror(\vx,\vxs) \in (e^L, e^R)$${#eq-ci-OR-exp}

:::

---

:::{#exr-or-diff-logodds}

Find a 95% confidence interval for the log of the odds ratio,
$\logf{\ror(\vx,\vxs)}$

:::

---

:::{#sol-or-diff-logodds}

From @cor-log-or, we know:

$$\logf{\ror(\vx,\vxs)} = \difflogodds$$

By @thm-dist-mle,
a 95% confidence interval for $\difflogodds$
can be constructed as:

$$\hdifflogodds \pm 1.96 * \blue{\HSE{\hdifflogodds}}$$

:::

---

:::{#exr-se-diff-logodds}

::: notes
How can we estimate the standard error of
$\hdifflogodds$?
:::

$$\blue{\HSE{\hdifflogodds}} = \blue{?}$$

:::

---

:::{#sol-se-diff-logodds}

$$
\green{\SE{\hdifflogodds}} = 
\sqrt{\red{\Var{\hdifflogodds}}}
$${#eq-se-sqrt-var}

By @lem-diff-logodds and @thm-var-lincom:

$$
\ba
\red{\Var{\hdifflogodds}}
&= \Var{(\diffvx) \cdot \hb}
\\
&= \pt{\diffvx}\Cov{\hb}(\diffvx)
\\
&= \red{\pt{\diffvx}\Sigma(\diffvx)}
\ea
$${#eq-var-diff-logodds}

where $\Sigma \eqdef \Covt(\hb)$.

---

::: notes
Expanding @eq-var-diff-logodds out of matrix-vector notation, we have:
:::

$$
\ba
\red{\pt{\diffvx}\Sigma(\diffvx)}
&= \sumip\sumjp (\diffvx)_i \Sigma_{ij} (\diffvx)_j
\\
&= \sumip\sumjp (\Delta x_i) \Sigma_{ij} (\Delta x_j)
\\
&= \red{\sumip\sumjp (x_i - x^*_i) \Covt(\hb_i,\hb_j) (x_j - x^*_j)}
\ea
$$

---

Combining @eq-var-diff-logodds and MLE invariance:

:::{#thm-est-se-diff-logodds}

#### Estimated variance and standard error of difference in log-odds

$$
\orange{\hVar{\Delta{\hat\logodds}}} = \orange{\tp{\diffvx}\hat{\Sigma}(\diffvx)}
$${#eq-est-var-difflogodds}

$$
\blue{\HSE{\Delta{\hat\logodds}}} = 
\blue{\sqrt{\tp{\diffvx}\hat{\Sigma}(\diffvx)}}
$${#eq-est-se-diff-logodds}

:::

::: notes
Note: on the RHS, we have plugged in $\hat{\Sigma}$, 
our estimate of $\Sigma$.

Compare this result with @sec-se-fitted.

:::

:::
