
### Distributions of Time-to-Event Data  {.smaller}

-   The distribution of event times is asymmetric and can be long-tailed,
and starts at 0 (that is, $P(T<0) = 0$).
-   The base distribution is not normal, but exponential.
-   There are usually **censored** observations, which are ones in which
the failure time is not observed.
-   Often, these are **right-censored**,
meaning that we know that the event occurred after some known time $t$,
but we don't know the actual event time,
as when a patient is still alive at the end of the study.
-   Observations can also be **left-censored**,
meaning we know the event has already happened at time $t$,
or **interval-censored**,
meaning that we only know that the event happened between times $t_1$ and $t_2$.
-   Analysis is difficult if censoring is associated with treatment.

### Right Censoring

-   Patients are in a clinical trial for cancer, some on a new treatment
and some on standard of care.
-   Some patients in each group have died by the end of the study. We
know the survival time (measured for example from time of
diagnosis---each person on their own clock).
-   Patients still alive at the end of the study are right censored.
-   Patients who are lost to follow-up or withdraw from the study may be
right-censored.

### Left and Interval Censoring

-   An individual tests positive for HIV.
-   If the event is infection with HIV, then we only know that it has
occurred before the testing time $t$, so this is left censored.
-   If an individual has a negative HIV test at time $t_1$ and a
positive HIV test at time $t_2$, then the infection event is
interval censored.
