{{< include latex-macros/macros.qmd >}}

:::{#exr-def-logistic-regression}

What is logistic regression?

:::

---

:::{#sol-def-logistic-regression}

:::{#def-logistic-regression}
**Logistic regression** is a framework for modeling [binary](probability.qmd#def-binary) outcomes, conditional on one or more *predictors* (a.k.a. *covariates*).
:::

:::

---

::: {#exr-binary-examples}

#### Examples of binary outcomes

What are some examples of binary outcomes in the health sciences?
:::

----

:::: {#sol-binary-examples}

{{< include binary-outcome-examples.qmd >}}


::::

---

Logistic regression uses the [Bernoulli](probability.qmd#def-bernoulli) distribution to model the outcome variable, conditional on one or more covariates.

---

::: {#exr-def-bernoulli}

Write down a mathematical definition of the Bernoulli distribution.
:::

---

::::{#sol-def-bernoulli}

{{< include def-bernoulli.qmd >}}

::::

---

### Logistic regression versus linear regression

Logistic regression differs from linear regression, which uses the Gaussian ("normal") distribution to model the outcome variable, conditional on the covariates.

---

:::: {#exr-examples-linreg}

Recall: what kinds of outcomes is linear regression used for?
::::

---

::: {#sol-examples-linreg}

Linear regression is typically used for numerical outcomes that aren't event counts or waiting times for an event.

Examples of outcomes that are often analyzed using linear regression include:

- weight
- height
- income
- prices

:::
