:::{#exr-def-regression}
What is a regression model?
:::

---

:::{#def-regression-model}
#### Regression model
Regression models
are conditional probability distribution models:

$$\P(Y|\vX)$$
:::

---

:::{#exr-name-regression-model-variables}

What are some of the names used for the variables in a regression model $\P(Y|\vX)$?

:::

---

:::{#def-outcome}
#### Outcome
The outcome variable in a regression model
is the variable whose distribution is being described;
in other words, the variable on the left-hand side of the "|" ("pipe") symbol.

The outcome variable is also called the
**response variable**,
**regressand**,
**predicted variable**,
**explained variable**,
**experimental variable**,
**output variable**,
**dependent variable**,
**endogenous variables**,
**target**,
or
**label**.

and is typically denoted $Y$.
:::

---

:::{#def-predictors}

#### Predictors

The predictor variables in a regression model are the conditioning variables
defining subpopulations among which the outcome distribution might vary.

Predictors are also called
**regressors**,
**covariates**,
**independent variables**,
**explanatory variables**,
**risk factors**,
**exposure variables**,
**input variables**,
**exogenous variables**,
**candidate variables** (@dunn2018generalized),
**carriers** (@dunn2018generalized),
**manipulated variables**,
or
**features**
and are typically denoted $\vX$.
^[The "~" ("tilde") symbol in the notation $\vX$ indicates that $\vX$ is a vector.
See [the appendices](notation.qmd) for a table of notation used in these notes.]

:::

---

::: {#tbl-regression-antonyms .smaller}

$\vX$ | $Y$ | usual context
----- | ------ | ----
input | output |
independent | dependent |
predictor | predicted or response |
explanatory | explained |
exogenous | endogenous | econometrics
manipulated | measured | randomized controlled experiments
exposure | outcome | epidemiology
feature | label or target | machine learning

Common pairings of terms for variables $\vX$ and $Y$ in regression models $P(Y|\vX)$ ^[adapted from <https://en.wikipedia.org/wiki/Dependent_and_independent_variables#Synonyms>]

:::
