
::: notes
@tbl-oc-mi simulates a follow-up study in which two populations were followed and the number of MI’s was observed.
The risks are $P(MI|OC)$ and $P(MI|\neg OC)$ and we can estimate these risks from the data.

But suppose we had a case-control study in which we had 100 women with MI and selected a comparison group of 100 women without MI (matched as groups on age, etc.).
Then MI is not random, and we cannot compute P(MI|OC) and we cannot compute the risk ratio.
However, the odds ratio however can be computed.

The disease odds ratio is the odds for the disease in the exposed group divided by the odds for the disease in the unexposed group, and we cannot validly compute and use these separate parts.

We can still validly compute and use the exposure odds ratio,
which is the odds for exposure in the disease group divided by the odds for exposure in the non-diseased group
(because exposure can be treated as random):

:::

$$
\hth(OC|MI) =
\frac{\hat{\odds}(OC|MI)}{\hat{\odds}(OC|\neg MI)}
$$

::: notes
And these two odds ratios, $\hth(MI|OC)$ and $\hth(OC|MI)$,
are mathematically equivalent, as we saw in @sec-OR-props:
:::

$$\hth(MI|OC) = \hth(OC|MI)$$

---

:::{#exr-or-rev}

Calculate the odds ratio of MI with respect to OC use,
assuming that @tbl-oc-mi comes from a case-control study.
Confirm that the result is the same as in @exm-OR.

:::

---

:::: {.solution}

:::{#tbl-oc-mi2}

```{r}
tbl_oc_mi |> pander::pander()
```

Simulated data from study of oral contraceptive use and heart attack risk

:::

* $\odds(OC|MI) = P(OC|MI)/(1 – P(OC|MI) = \frac{13}{7} = `r 13/7`$

* $\odds(OC|\neg MI) = P(OC|\neg MI)/(1 – P(OC|\neg MI) = \frac{4987}{9993} = `r 4987/9993`$

* $\theta(OC,MI) = \frac{\odds(OC|MI)}{\odds(OC|\neg MI)} = \frac{13/7}{4987/9993} = `r (13/7)/(4987/9993)`$

::: notes
This is the same estimate we calculated in @exm-OR.
:::

::::
