@dobson4e [§2.1] describes the model fitting process as follows:

> The model fitting process described in this book involves four steps:
>
> 1. Model specification—a model is specified in two parts:
> an equation linking the response and explanatory variables
> and the probability distribution of the response variable.
>
> 2. Estimation of the parameters of the model.
>
> 3. Checking the adequacy of the model—how well it fits or summarizes the data.
>
> 4. Inference—for classical or frequentist inference
> this involves calculating confidence intervals,
> testing hypotheses about the parameters in the model
> and interpreting the results.

Note that @dobson4e omits exploratory data analysis (EDA) from this initial list,
but describes it later as an important preliminary step (@dobson4e [§2.3.1]).
We will treat EDA as a "step 0" that precedes the four steps above.

## Step 0: Exploratory data analysis

@dobson4e [§2.3.1]:

> Any analysis of data should begin with a consideration of each variable
> separately,
> both to check on data quality
> (for example, are the values plausible?)
> and to help with model formulation.
>
> 1. What is the scale of measurement?
> Is it continuous or categorical?
> If it is categorical,
> how many categories does it have
> and are they nominal or ordinal?
>
> 2. What is the shape of the distribution?
> This can be examined using frequency tables,
> dot plots,
> histograms
> and other graphical methods.
>
> 3. How is it associated with other variables?
> Cross tabulations for categorical variables,
> scatter plots for continuous variables,
> side-by-side boxplots for continuous scale measurements
> grouped according to the factor levels of a categorical variable,
> and other such summaries can help to identify patterns of association.
> For example, do the points on a scatter plot suggest
> linear or non-linear associations?
> Do the group means increase or decrease consistently
> with an ordinal variable defining the groups?
