{{< include macros.qmd >}}

:::{#thm-odds-to-prob}

If $\pi$ is the probability of an event
and $\omega$ is the corresponding odds of that event,
then:

$$\pi = \frac{\odds}{1+\odds}$${#eq-prob-from-odds}

:::

---

::: proof
Start from @thm-prob-to-odds and solve for $\prob$ in terms of $\odds$.
:::

---

:::{#def-inv-odds}

##### inverse odds function

$$
\invoddsf{\odds} \eqdef \frac{\odds}{1 + \odds}
$${#eq-invodds-fn}

can be called the **inverse-odds function**.

:::

::: notes
The inverse-odds function converts odds into their corresponding probabilities (@fig-inv-odds).
Its domain of inputs is $\omega \in [0,\infty)$ and its range of outputs is $\pi \in [0,1]$.

I haven't seen anyone give the inverse-odds function a concise name; maybe $\probt()$ or $\probst()$ or $\riskt()$?
:::

---

:::{#cor-invodds-pi}

$$\prob = \invoddsf{\odds}$$
:::

---

:::{#fig-inv-odds}
```{r}
odds_inv <- function(omega) (1 + omega^-1)^-1
library(ggplot2)
ggplot() +
  geom_function(fun = odds_inv, aes(col = "inverse-odds")) +
  xlab("Odds") +
  ylab("Probability") +
  xlim(0, 5) +
  ylim(0, 1) +
  geom_abline(aes(intercept = 0, slope = 1, col = "x=y"))
```

The inverse odds function, $\invoddsf{\odds}$
:::

---

:::{#exr-odds-probs}

What probability corresponds to an odds of $\odds = 1$, and what is the numerical difference between these two values?

:::

---

::::{.solution}
$$
\pi(1) = \frac{1}{1+1}
=\frac{1}{2}
= .5
$$
$$
1 - \pi(1) = 1 - .5 = .5
$$

::::

---

:::{#lem-invodds-simplified}

##### Simplified expression for inverse odds function

::: notes
Equivalent expressions for the inverse odds function are:
:::

$$
\ba
\pi(\odds) 
&= \frac{1}{1+\odds^{-1}}
\\
&= (1+\odds^{-1})^{-1}
\ea
$$ {#eq-inv-odds-reduced}

:::

---

:::{#exr-inv-odds2}
Prove that @eq-inv-odds-reduced is equivalent to @def-inv-odds.
:::

---

:::{#sol-inv-odds2}

Analogous to @sol-odds2.

:::

---


:::{#lem-one-minus-odds-inv}
#### One minus inverse-odds

$$1 - \oddsinvf{\odds} = \frac{1}{1+\odds}$$

:::

---

::: {.proof}

$$
\ba
1 - \oddsinvf{\odds} &= 1 - \frac{\odds}{1 + \odds}
\\ &= \frac{\red{1+\odds}}{1 + \odds} - \frac{\blue{\odds}}{1 + \odds}
\\ &= \frac{\red{(1+\odds)} - \blue{\odds}}{1 + \odds}
\\ &= \frac{1 + \odds - \odds}{1 + \odds}
\\ &= \frac{1}{1 + \odds}
\ea
$$

:::

---

:::{#lem-inverse-odds-nonevent}

If $\odds$ is the odds of event $A$,
then the probability that $A$ does not occur is:

$$\Pr(\neg A) = \frac{1}{1+\odds}$$

:::

---

::: proof

:::: notes
Use @cor-p-neg0 and @lem-one-minus-odds-inv:
::::

$$
\ba
\Pr(\neg A)
&= 1 - \Pr(A)
\\ &= 1 - \oddsinvf{\odds}
\\ &= \frac{1}{1 + \odds}
\ea
$$
:::

---

:::{#cor-inverse-odds-nonevent}

If $\prob$ is the probability of event $A$ 
and $\odds$ is the corresponding odds of event $A$,
then:

$$1-\pi = \frac{1}{1+\odds}$$
:::

---

::: proof

Combine @lem-inverse-odds-nonevent and @cor-p-neg.

:::

---

:::{#lem-deriv-invodds}

##### Derivative of inverse odds function
$$\doddsinvf{\odds} = \frac{1}{\sqf{1+\odds}}$$
:::

---

::: proof

:::: notes
Use the quotient rule:
::::

$$
\ba
{\oddsinv}'(\odds)
&= \deriv{\odds} \oddsinvf{\odds}
\\ &= \deriv{\odds} \frac{\odds}{1+\odds}
\\ &= \frac{\deriv{\odds}\odds}{1+\odds} - \frac{\odds}{\sqf{1+\odds}} \cd \deriv{\odds}(1+\odds)
\\ &= \frac{1}{1+\odds} - \frac{\odds}{\sqf{1+\odds}} \cd 1
\\ &= \frac{1}{1+\odds} - \frac{\odds}{\sqf{1+\odds}}
\\ &= \frac{1+\odds}{\sqf{1+\odds}} - \frac{\odds}{\sqf{1+\odds}}
\\ &= \frac{1+\odds - \odds}{\sqf{1+\odds}}
\\ &= \frac{1}{\sqf{1+\odds}}
\ea
$$

:::

---


:::{#cor-deriv-invodds}

$$\doddsinvf{\odds} = \sqf{1 - \oddsinvf{\odds}}$$
:::

---

:::{#cor-deriv-invodds-pi-scale}

$$\doddsinvf{\odds} = (1-\pi)^2$$

:::

---

::: proof

Combining @cor-inverse-odds-nonevent and @lem-deriv-invodds:

$$
\ba
\doddsinvf{\odds} &= \sqf{\frac{1}{1+\omega}}
\\
&= (1-\pi)^2
\ea
$$
:::

---

:::{#cor-d_prob-d_odds}

$$\derivf{\prob}{\odds} = (1-\prob)^2$${#eq-d_prob-d_odds}

:::

---

::: proof

By @cor-deriv-invodds-pi-scale:

$$
\ba
\derivf{\pi}{\omega} &= \deriv{\omega} \oddst^{-1}(\odds)
\\
&= (1-\pi)^2
\ea
$$

Alternatively, by @cor-d_odds-d_prob:

$$
\ba
\derivf{\prob}{\odds} 
&= \invf{\derivf{\odds}{\prob}}
\\
&= \invf{\frac{1}{\sqf{1-\prob}}}
\\
&= \sqf{1-\prob}
\ea
$$

:::

