---
subtitle: "Poisson regression and variations"
---

# Models for Count Outcomes

---

## Acknowledgements {.unnumbered}

This content is adapted from:

-   @dobson4e, Chapter 9
-   @vittinghoff2e, Chapter 8

---

{{< include shared-config.qmd >}}

## Introduction

{{< include _sec_pois-reg_intro.qmd >}}

## Interpreting Poisson regression models {.smaller}

{{< include _sec_poisson_RRs.qmd >}}

## Inference for count regression models

{{< include _sec_poisson_inference.qmd >}}

## Prediction

{{< include _sec_pois-reg-preds.qmd >}}

## Diagnostics

{{< include _sec_poisson_dx.qmd >}}


## Zero-inflation
{{< include _sec_zero-inflation.qmd >}}

## Over-dispersion

{{< include _sec-overdispersion.qmd >}}
---

{{< include _note_glm-naming.qmd >}}

---

### Negative binomial models

::: notes
There are alternatives to the Poisson model.
Most notably, 
the [negative binomial model](probability.qmd#sec-nb-dist).

We can still model $\mu$ as a function of $X$ and $T$ as before, 
and we can combine this model with zero-inflation 
(as the conditional distribution for the non-zero component).
:::

### Quasipoisson

An alternative to Negative binomial is the "quasipoisson" distribution. I've never used it, but it seems to be a method-of-moments type approach rather than maximum likelihood. It models the variance as $\Var{Y} = \mu\theta$, and estimates $\theta$ accordingly.

See `?quasipoisson` in R for more.

## Example: needle-sharing

(adapted from @vittinghoff2e, ยง8)

{{< include exr-needle-sharing.qmd >}}

## More on count regression

- <https://bookdown.org/roback/bookdown-BeyondMLR/ch-poissonreg.html>
