---
title: "Exam Formula Sheet"
format: 
  pdf:
    output-file: exam-formula-sheet-handout.pdf
    toc: false
  html:
    code-link: false
---

```{r, eval = FALSE, include = FALSE}

# quarto render "exam-formula-sheet.qmd" --profile "handout"
```

{{< include latex-macros/macros.qmd >}}

# Epi 202: Probability

{{< include _subfiles/probability/_eq_var_lincom.qmd >}}

$$\Expf{Y} = \Expf{\Expf{Y \mid X}}$$

$$\Expf{Y \mid Z} = \Expf{\Expf{Y \mid X,Z} | Z}$$

$$\Var{Y} = \Expf{\Var{Y \mid X}} + \Var{\Expf{Y \mid X}}$$

$$\Cov{Y,Z} = \Expf{\Cov{Y,Z \mid X}} + \Cov{\Expf{Y \mid X}, \Expf{Z \mid X}}$$

# Epi 203: Statistical inference

$$\defLik$$

$$\defLogLik$$

$$\defScore$$

$$\defHess$$

$$\thmHessij$$

$$\defOInf$$
$$\defEInf$$

$$\thmADistMLE$$

For one parameter $\theta_k$:

$$
\text{CI}_{1-\alpha}(\theta_k)
=
\left[
\hth_k
\pm
\za
\HSE{\hth_k}
\right]
$$

$$
Z_k
\eqdef
\frac{\hth_k-\theta_{k,0}}{\HSE{\hth_k}}
\ddist
\ndist{0,1}
\qquad
\text{under }H_0:\theta_k=\theta_{k,0}
\qquad
z_k\text{ = observed }Z_k
$$

$$
\ba
p\text{-value}
&= 2\Pr \paren{\abs{Z}\ge \abs{z_k}},\quad Z\sim \ndist{0,1}
\\
&= 2\paren{1-\Phi\paren{\abs{z_k}}}
\ea
$$

# Sta 108: Linear regression

$$
t_k
\eqdef
\frac{\hb_k-\beta_{k,0}}{\HSE{\hb_k}}
\ddist
t_{n-p}
\qquad
\text{under }H_0:\beta_k=\beta_{k,0}
\qquad
t_k^{\text{obs}}\text{ = observed }t_k
$$

$$
\text{CI}_{1-\alpha}(\beta_k)
=
\left[
\hb_k
\pm
t_{n-p}\paren{1-\frac{\alpha}{2}}
\HSE{\hb_k}
\right]
$$

$$
\ba
p\text{-value}
&=
2\Pr \paren{\abs{T_{n-p}}\ge \abs{t_k^{\text{obs}}}}
\\
&=
2\paren{1-F_{t_{n-p}}\paren{\abs{t_k^{\text{obs}}}}}
\ea
$$

$$
\text{CI}_{1-\alpha}\paren{\mu\paren{\vxs}}
=
\left[
\hat{\mu}\paren{\vxs}
\pm
t_{n-p}\paren{1-\frac{\alpha}{2}}
\HSE{\hat{\mu}\paren{\vxs}}
\right]
$$

$Y^*$ denotes a new observation
(not in the training data),
with corresponding covariate pattern $\vxs$.

$$
\text{PI}_{1-\alpha}\paren{Y^*|\vxs}
=
\left[
\hat{Y}^*
\pm
t_{n-p}\paren{1-\frac{\alpha}{2}}
\HSE{Y^*-\hat{Y}^*}
\right]
$$

$$
\HSE{Y^*-\hat{Y}^*}
=
\hs\sqrt{1 + \tp{(\vxs)}(\mX'\mX)^{-1}\vxs}
$$

$$
\Var{Y^* - \hat{Y}^*}
= \sigma^2\paren{1 + \tp{(\vxs)}(\mX'\mX)^{-1}\vxs}
$$

Let $\hat{\Sigma} \eqdef \hVar{\hb} = \hs^2(\mX'\mX)^{-1}$.

$$
\hVar{\hat\mu(\vx)} = \tp{\vx}\hat{\Sigma}\vx
$$

Let $\Delta\mu}(\vx, \vxs) = \mu(\vx) - \mu(\vxs)$, and let $\diffvx = \vx - \vxs$; 
then:

$$
\hVar{\widehat{\Delta\mu}(\vx, \vxs)} = \tp{\diffvx}\hat{\Sigma}(\diffvx)
$$

{{< pagebreak >}}

# Epi 204: Generalized linear models

{{< include _subfiles/Intro-to-GLMs/_sec_glm_structure_brief.qmd >}}

{{< include _subfiles/logistic-regression/_sec_logistic-link-diagram.qmd >}}

$$\eqGLMRatio$$

## Estimates of odds ratios from 2x2 contingency tables

$$\hth =\frac{ad}{bc}$$

{{< pagebreak >}}

<!-- ### Logistic model interpretation -->

<!-- {{< include _subfiles/logistic-regression/_sec_wcgs_notation.qmd >}} -->

<!-- {{< include _subfiles/logistic-regression/_eq_wcgs_model_1.qmd >}} -->

<!-- {{< include _subfiles/misc/_sec-logistic-interp-formulas.qmd >}} -->

<!-- {{< pagebreak >}} -->

## Survival analysis

### Probability distribution functions

{{< include _subfiles/probability/_sec-survival-dist-fns.qmd >}}

### Diagram of survival distribution function relationships

{{< include _subfiles/shared/_surv_diagram.qmd >}}

### Survival likelihood contributions, assuming non-informative censoring

$$
\ba
\p(Y=y,D=d) 
&= [\pdf_T(y)]^{d} [\surv_T(y)]^{1-d}
\\
&= [\haz_T(y)]^{d} [\surv_T(y)]
\ea
$$

### Nonparametric time-to-event distribution estimators

{{< include _subfiles/intro-to-survival-analysis/_eq-def-km-surv-est.qmd >}}

{{< include _subfiles/intro-to-survival-analysis/_eq-NA-cuhaz-est.qmd >}}

{{< pagebreak >}}

### Proportional hazards model structure

{{< include _subfiles/proportional-hazards-models/_coxph-model-structure.qmd >}}

{{< pagebreak >}}

### Proportional hazards model partial likelihood formula:

{{< include _subfiles/proportional-hazards-models/_def-ph-partial-lik.qmd >}}

### Proportional hazards model baseline cumulative hazard estimator:

{{< include _subfiles/proportional-hazards-models/_def-breslow-baseline-cuhaz-est.qmd >}}
