```{r}
library(tidyverse)
library(haven)
needles = 
  "inst/extdata/needle_sharing.dta" |> 
  read_dta() |>
  as_tibble() |>
  mutate(
    hivstat =
      hivstat |>
      case_match(
        1 ~ "HIV+",
        0 ~ "HIV-") |> 
      factor() |> 
      relevel(ref = "HIV-"),
    polydrug =
      polydrug |>
      case_match(
        1 ~ "multiple drugs used",
        0 ~ "one drug used") |>
      factor() |>
      relevel(ref = "one drug used"),
    homeless = 
      homeless |> 
      case_match(
        1 ~ "homeless", 
        0 ~ "not homeless") |>
      factor() |>
      relevel(ref = "not homeless"),
    ethn = ethn |> factor() |> relevel(ref = "White"),
    sex = sex |> factor() |> relevel(ref = "M")
  ) |> 
  labelled::set_variable_labels(
    "sex" = "sex (reference = Male)",
    "ethn" = "ethnicity (reference = White)",
    "shsyryn"  = "shared syringe yes/no (1 = yes, 0 = no)",
    "logshsyr" = "log(No. of shared needles)",
    "polydrug" = "how many drugs used?",
    "sqrtninj" = "sqrt(No. of infections in 30 days)",
    "homeless" = "Homeless (1 = yes, 0 = no)",
    "hivstat" = "HIV status (reference = HIV-)"
  )
```

:::{#tbl-needles-data-dict}

```{r}
dict <- tibble(
  variable = names(needles),
  description = labelled::get_variable_labels(needles) |> 
    sapply(function(x) ifelse(is.null(x), "", x)),
)
dict |> pander::pander()
```

Data dictionary for `needles` data

:::

---

```{r}
#| tbl-cap: "Needle-sharing data"
#| label: tbl-needle-data
needles
```

---

```{r}
#| fig-cap: "Rates of needle sharing"
#| label: fig-needles
library(ggplot2)

needles |> 
  ggplot(
    aes(
      x = age,
      y = shsyryn,
      shape = sex,
      col = ethn
    )
  ) + 
  geom_point(
    aes(size = nivdu), 
    alpha = .5) +
  scale_size_area(max_size = 4) +
  facet_grid(
    cols = vars(polydrug), 
    rows = vars(homeless)) +
  theme(legend.position = "bottom")
```

---

#### Covariate counts

```{r}
#| tbl-cap: "Counts of observations in `needles` dataset by sex, unhoused status, and multiple drug use"
#| label: tbl-count-needles
#| code-fold: show
needles |> 
  dplyr::select(sex, homeless, polydrug) |> 
  summary()
```

---

There's only one individual with `sex = Trans`, 
which unfortunately isn't enough data to analyze.
We will remove that individual:

```{r}
#| label: remove-trans-obs
#| code-summary: 'remove singleton observation with sex == Trans'
needles = needles |> filter(sex != "Trans")

```

---

### Model {.smaller}

```{r}
glm1 = 
  needles |> 
  dplyr::filter(nivdu > 0) |> 
  glm(
    offset = log(nivdu),
    family = stats::poisson,
    formula = shared_syr ~ age + sex + homeless*polydrug
  )
library(equatiomatic)
equatiomatic::extract_eq(glm1)
```

---

```{r}
#| tbl-cap: "Poisson model for needle-sharing data"
#| label: tbl-needles-pois


library(parameters)
glm1 |> parameters(exponentiate = TRUE) |> 
  print_md()
```

---

```{r}
#| tbl-cap: "fitted Poisson model for needle-sharing data"
#| label: fig-needles-pois
library(sjPlot)
glm1 |> 
  sjPlot::plot_model(
    type = "pred",
    terms = c("age", "sex", "homeless", "polydrug"),
    show.data = TRUE
  ) +
  theme(legend.position = "bottom")
```

