---
title: "Introduction to Multi-level Models"
format:
  html: default
  revealjs:
    output-file: intro-multilevel-models-slides.html
  pdf:
    output-file: intro-multilevel-models-handout.pdf
---

# Introduction to multi-level models for correlated data


For more, see:

* [David Rocke](https://dmrocke.ucdavis.edu/)'s materials from the 
[2021 edition of this course](
https://dmrocke.ucdavis.edu/Class/EPI204-Spring-2021/EPI204-Spring-2021.html) 
  * May 25 - June 1 lectures


* Other UC Davis courses:
  - [EVE 225](https://catalog.ucdavis.edu/search/?q=EVE+225):
"Linear Mixed Modeling in Ecology & Evolution"
     - usually taught every other winter or spring 
     by [Kate Laskowski](https://eve.ucdavis.edu/people/kate-laskowski)
     - materials, including syllabus and lecture videos: 
     <https://laskowskilab.faculty.ucdavis.edu/teaching-2/>
  - [STA/BST 224](https://catalog.ucdavis.edu/search/?P=BST%20224):
  "Analysis of Longitudinal Data"
     - usually taught every spring by [Shuai Chen](https://shuaichen.weebly.com/)
     - should be accessible after completing Epi 204
  - [EPI 226](https://catalog.ucdavis.edu/search/?P=EPI+226) "Methods for Longitudinal & Repeated Measurement Data"
     - usually taught by [Heejung Bang](https://biostat.ucdavis.edu/people/heejung-bang)
  - [PSC 205D](https://catalog.ucdavis.edu/search/?q=PSC+205D) "Multilevel Models"
  - [PSC 205G](https://catalog.ucdavis.edu/search/?q=PSC+205G) "Applied Longitudinal Data Analysis"
  - [STA 101](https://catalog.ucdavis.edu/search/?q=STA+101) "Advanced Applied Statistics for the Biological Sciences"
  - [STA 207](https://catalog.ucdavis.edu/search/?q=STA+207) "Statistical Methods for Research II"
  - [STA 232B](https://www.stat.ucdavis.edu/~jiang/sta232b.html) "Applied Statistics II"
     - usually taught every winter by [Jiming Jiang](https://www.stat.ucdavis.edu/~jiang/)
  - [PLS 207](https://catalog.ucdavis.edu/search/?q=PLS+207): 
"Applied Statistical Modeling for the Environmental Sciences"
  - [EDU 236](https://catalog.ucdavis.edu/search/?q=EDU+236): 
  "Application of Hierarchical Linear Models in Education Research"
  - [HDE 205](https://catalog.ucdavis.edu/search/?q=HDE+205): "Longitudinal Data Analysis"

* Books:
  - @dobson4e [Chapter 11](https://www.taylorfrancis.com/chapters/mono/10.1201/9781315182780-11/clustered-longitudinal-data-annette-dobson-adrian-barnett?context=ubx&refId=95f6c50e-093a-4488-a042-92a9f151a4b5)
  - @vittinghoff2e [Chapter 7](https://link.springer.com/chapter/10.1007/978-1-4614-1353-0_7)
  - @gelman2006data
  - @jiming2021
     - by UC Davis Statistics Professor and GGE faculty member [Jiming Jiang](https://www.stat.ucdavis.edu/~jiang/)
  - @faraway2016extending
  - @mcculloch2008generalized
  - @hedeker2006
  - @wakefield2013
  - @zuur2009
  - @DigglePeter2013AoLD
  - @fitzmaurice2012
  - @fitzmaurice2009
  - @galecki2013
  - @congdon2020
  - @molenberghs2005
  - @VerbekeGeert2000LMMf
  - @jewell2016analysis
      - by UC Berkeley professors
  
