# Introduction to Survival Analysis

{{< include shared-config.qmd >}}

## Overview

### Time-to-event outcomes {.smaller}

**Survival analysis** is a framework for modeling *time-to-event* outcomes. It is used in:

-   clinical trials, where the event is often death or
recurrence of disease.
-   engineering reliability analysis, where the event is
failure of a device or system.
-   insurance, particularly life insurance, where the
event is death.

:::{.callout-note}
The term *survival analysis* is a bit misleading. Survival outcomes can sometimes be analyzed using binomial models (logistic regression). *Time-to-event models* or *survival time analysis* might be a better name.
:::

## Time-to-event outcome distributions

{{< include _sec-surv-vars.qmd >}}

## Distribution functions for time-to-event variables

{{< include _sec-surv-dists.qmd >}}

## Parametric Models for Time-to-Event Outcomes

{{< include _sec-surv-intro-parametric-models.qmd >}}

## Nonparametric Survival Analysis

{{< include _sec-surv-nonparametric-surv-intro.qmd >}}

## Example: clinical trial for pediatric acute leukemia

{{< include _sec-surv-6mp.qmd >}}

## The Kaplan-Meier Product Limit Estimator

{{< include _sec-surv-KM.qmd >}}

## Using the `survival` package in R

{{< include _sec-surv-R.qmd >}}

## The log-rank test

{{< include _sec-surv-logrank-test.qmd >}}

## Example: Bone Marrow Transplant Data

{{< include _sec-surv-exm-bmt.qmd >}}

## Nelson-Aalen Estimates of Cumulative Hazard and Survival

{{< include _sec-surv-nelson-aalen.qmd >}}
