---
subtitle: "Logistic regression and variations"
---

# Models for Binary Outcomes {#sec-Bernoulli-models}

---

{{< include shared-config.qmd >}}

```{r}
options(digits = 6)
```


### Acknowledgements {.unnumbered}

This content is adapted from:

-   @dobson4e, Chapter 7
-   @vittinghoff2e, Chapter 5
- [David Rocke](https://dmrocke.ucdavis.edu/)'s materials from the [2021 edition of Epi 204](https://dmrocke.ucdavis.edu/Class/EPI204-Spring-2021/EPI204-Spring-2021.html)
-   @NahhasIRMPHR [Chapter 6](https://www.bookdown.org/rwnahhas/RMPH/blr.html)

## Introduction

---

{{< include _sec_overview_bernoulli_models.qmd >}}

{{< include _sec_intro_bernoulli_models.qmd >}}

## Introduction to logistic regression

{{< include _sec_one_cov_logistic.qmd >}}

## Derivatives of logistic regression functions

{{< include _sec_logistic-reg-derivatives.qmd >}}

## Understanding logistic regression models

{{< include _sec_logistic_slope_mean.qmd >}}

---

{{< include _sec_derivs_MLE.qmd >}}

---

{{< include _sec_OR_logistic.qmd >}}

## Estimating logistic regression models

{{< include _sec_logistic-fitting.qmd >}}

## Inference for logistic regression models

### Inference for individual predictor coefficients

#### Wald tests and confidence intervals

(to be added)

### Inference for odds ratios

{{< include _sec_OR_inference.qmd >}}

## Multiple logistic regression

{{< include _sec_exm_wcgs.qmd >}}

## Model comparisons for logistic models {#sec-gof}

{{< include _sec_logistic_gof.qmd >}}

## Residual-based diagnostics

{{< include _sec_logistic_dx.qmd >}}

## Alternatives to reporting odds ratios

{{< include _sec_OR_objections.qmd >}}

## Other link functions for Bernoulli outcomes

{{< include _sec-non-logistic-bernoulli-models.qmd >}}

## Quasibinomial

See [Hua Zhou](https://hua-zhou.github.io/)'s [lecture notes](https://ucla-biostat-200c-2020spring.github.io/slides/04-binomial/binomial.html#:~:text=0.05%20%27.%27%200.1%20%27%20%27%201-,Quasi%2Dbinomial,-Another%20way%20to)


## Further reading

- @hosmer2013applied is a classic textbook on logistic regression
