# Mathematics

{{< include macros.qmd >}}

---

> Math is not just a way of calculating numerical answers; 
it is a way of thinking, 
using clear definitions for concepts and rigorous logic 
to organize our thoughts and back up our assertions.

@cheng2025math

---

These lecture notes use:

- algebra
- precalculus
- univariate calculus
- linear algebra
- vector calculus

Some key results are listed here.

{{< include algebra.qmd >}}

## Derivatives

{{< include calc-derivatives.qmd >}}

## Linear Algebra

{{< include _def_lincom.qmd >}}

## Vector Calculus {#sec-vector-calculus}

{{< include _sec_vector_calc.qmd >}}

## Additional resources

### Calculus 

- @mosaiccalc
- @khuri2003advanced
- @calclifesaver
- @problifesavercalc
   - <http://www.youtube.com/watch?v=xYzQL0TUtBA>
   - <http://www.youtube.com/watch?v=Ps2SBo_WjoE>

### Linear Algebra and Vector Calculus

- @fieller2018basics
- @banerjee2014linear
- @searle2017matrix

### Numerical Analysis

- [Hua Zhou](https://hua-zhou.github.io/)'s [lecture notes for "UCLA Biostat 216 - Mathematical Methods for Biostatistics" (2023 Fall)](https://ucla-biostat-216.github.io/2023fall/schedule/schedule.html)

### Real Analysis

- @realanalysislifesaver
