---
title: "Nonparametric time-to-event models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Nonparametric time-to-event models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
runtime: shiny
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

```{r setup}
# library(2023)
```

```{r}

na_kernel = function(n,d=1) exp(-d/n)
km_kernel = function(n,d=1) 1-(d/n)

```

```{r}
sliderInput("d", "# events", value = 1, min = 1, max = 1,step = 1)
```

```{r}
sliderInput("n", "# at risk", value = 10, min = 1, max = 100,step = 1)
```

```{r}
observeEvent(input$n, 
             {
               updateSliderInput(input = "d", max = input$n, value = min(input$n, input$d))
             })
{
  plot(function(x) na_kernel(x, d = input$d), xlim = c(input$d,input$n),ylim = c(0,1), xlab = "# at risk",
       ylab = "p(X>x|X>=x)")
  
  plot(function(x) km_kernel(x, d = input$d), add = TRUE, xlim = c(input$d,input$n), col = "red")
} |> renderPlot()

```


