This course will be taught entirely in-person. The class sessions will
not be digitally streamed or recorded. Class sessions will include a mix
of lectures and interactive data analysis exercises.

### Participation

Active participation in class is strongly encouraged. Please feel
welcome to interrupt class frequently to ask questions or to ask us to
slow down or repeat details that you missed.

The class scratch notebook is shared with course participants on Canvas
(the link is restricted to enrolled students).

### Schedule

This class will meet Tuesdays and Thursdays, 2:10pm--4:00pm, in Gladys
Valley Hall (<https://campusmap.ucdavis.edu/?b=178>) room 1010, starting
March 31, 2026, and concluding June 4, 2026. The preliminary schedule of
class session topics is on the [Schedule](schedule.qmd) page and on
[Canvas](https://canvas.ucdavis.edu/courses/1077308/files/folder/Logistics).

### Attendance

Attendance is not tracked or graded but is strongly recommended.
However, **do not attend class if you think you might be infectious**.
If you miss class, please review the lecture materials posted online,
confer with your classmates, and feel free to contact the instructor to
schedule a meeting if helpful.

### Equipment

You will need to bring a laptop (Mac, Windows, or Linux) to class every
day in order to participate in the data analysis exercises. Laptops can
be borrowed from the library:
<https://lsit.ucdavis.edu/request-loaner-equipment>

### Software

The applied data analysis exercises in class will use the R programming
language, which is free to download at <https://cran.r-project.org/>. R
is a very popular option for data analysis; you can find jobs for R
users here: <https://www.r-users.com/>. We will also use the RStudio
integrated development environment, which is free to download at
<https://posit.co/download/rstudio-desktop/>. Please try to install both
of these programs prior to the second day of class (Thursday, April 4).

As an alternative to installing software, you may choose to use the
cloud computing service [Posit Cloud](https://posit.cloud/); you can
sign up for the Free plan and join the workspace for this course
(join link available on Canvas),
which will provide access to additional compute hours for the duration
of this course. We can help you with any installation or sign-up issues
during the first week of class or during office hours.

For homework, you are strongly encouraged to use the R programming
skills taught in class. If you would prefer to use another programming
language, you may do so, but the instructor and TA may not be able to
guide you as effectively.
