Academic honesty is an important part of the integrity of the
University\'s education. All students are responsible for the academic
integrity of the UC Davis campus according to the UC Davis Code of
Academic Conduct. This code covers conduct during exams, plagiarism,
unauthorized collaboration, misuse of materials, fraud, lying,
intimidation or disruption. The full statement can be found
[here](https://studentconduct.ucdavis.edu/conduct/policies/student-conduct-and-discipline-interim#102.01.1).
See also: ["Suggestions for Avoiding Academic
Misconduct"](https://ossja.ucdavis.edu/suggestions-avoiding-academic-misconduct).

You are expected to come to class ready to learn and participate. You
are expected to treat your fellow students and the instructors with
professional respect, courtesy, sensitivity, and inclusion, in
accordance with the UC Davis Principles of Community
(<https://excellence.ucdavis.edu/principles-community/>). You should
likewise expect and require that the instructors treat you all with
professional respect, courtesy, sensitivity, and inclusion.

### Academic Conduct Specific to Epi 204

Cell phones must be silenced and put away during class. Do not
photograph or record instructors or TAs without explicit consent. Do not
take pictures of the board or screen; instead, please feel free to ask
for more time to handwrite or type up your notes. Taking notes is a
crucial practice and skill both for learning and for professional work.
