There will be five graded homework assignments, as well as additional
ungraded exercises and readings. Each homework assignment is worth 5% of
your final grade (25% cumulative). The homework assignments are always
due at 5pm Pacific (see
[schedule](https://canvas.ucdavis.edu/courses/1077308/files/folder/Logistics));
see Late Work policy below.

### Homework Submission Format

Homework submissions **must** be **typed** and **submitted digitally**
as a **PDF** [on
Canvas](https://canvas.ucdavis.edu/courses/1077308/assignments).
Regardless of whether you compose your submission in Quarto, RMarkdown,
MS Word, Google Docs, or any other system, you must convert it to PDF
before submitting. Doing so minimizes the chance that your submission
will look different to us than it does to you.

Homework solutions should use a journal article or technical report
format. Tables and figures should have numbers and captions, and their
source and interpretation should be explained in the main text of your
homework solution. Raw, uninterpreted software output is not acceptable;
please see in-class exercise solutions for examples.

Reports must have sufficient documentation to meet "reproducible
research" standards. We will introduce these standards in class. We
encourage using the Quarto system
(<https://quarto.org/docs/get-started/hello/rstudio.html>) to generate
reports; this system will be taught in class.

### Late Work

Requests for extensions due to foreseeable issues should be submitted at
least 24 hours prior to the due date (i.e., by 5pm Pacific time, one day
before the due date).

Unless otherwise noted, every assignment has an automatic **24-hour,
no-questions-asked extension, which will be programmed into Canvas by
allowing submissions without penalty for 24 hours after the due date.**
However, this course moves very quickly, and you should aim to submit
assignments on time.

If you have not submitted your homework by the extended deadline, you
are still encouraged to complete the assignments in order to learn the
material.

### Collaboration

We strongly encourage you to study together and discuss homework
problems. You are also encouraged to share questions and answers on
[Canvas
Discussions](https://canvas.ucdavis.edu/courses/1077308/discussion_topics).
However, you must list your collaborators at the top of your
submissions, and you must write up your final homework answers
individually to make sure you are learning the material. Do not turn in
work that is identical to any other student's work.

### Artificial Intelligence

You may use AI assistance if helpful (e.g., ChatGPT), but you are
ultimately responsible for the quality of your submitted work. Please
keep in mind that you will not have computer access during the exams!

### Homework Grading

After each homework submission deadline, solutions will be posted. **You
are encouraged to self-grade your homework assignments** **using the
posted solutions.** Accurately self-grading each homework is 1% of your
grade (5% cumulative).

The instructor and TA will spot-check your self-grading, and you are
encouraged to ask for help with self-grading during office hours.

Your self-graded homework solutions are due on Canvas at 5pm, 1 week
after the solutions are provided. **Self-grading should include
specific, detailed annotations on each sub-problem marking where you
made mistakes, what your mistake was, and what a correct answer would
have been. In other words, give yourself the feedback that you think an
ideal TA would give.** Handwritten self-grading annotations are
acceptable.

Self-grading serves multiple purposes:

- It enables the TA and instructor to spend more time on office hours
  and course preparation.

- It motivates the students to learn from their mistakes.

You are also welcome to opt out of self-grading, in whole or in part. If
you not complete your self-grading for an assignment by the
corresponding deadline, we will assume that you want us to grade it for
you, but we would be grateful for explicit notification when you decide
not to self-grade, which might enable us to provide feedback sooner.

**All questions and objections to grading by the instructor and TA must
be submitted in writing on Canvas.**

### Expected Study Workload

See
<https://academicsenate.ucdavis.edu/committees/courses-of-instruction/policies-procedures#Credit>:

> "At UC Davis, units of credit are assigned to courses based on the
> \"Carnegie rule\" which specifies **one unit of credit for three hours
> of work** by the student **per week**. Usually this involves one hour
> of lecture or discussion led by the instructor and two hours of
> outside preparation by the student."

This is a four-unit course, so you should plan to **spend up to eight
hours per week studying outside of class time**. Please actively manage
and track your time.

**If you find yourself spending more than eight hours per week on this
course**, please contact the instructor and TA to discuss how we can
help you become more efficient and effective in the course.

**Please track the time you spend on this course.** Accurately tracking
your time is an important habit to build for your career. If you have
concerns about the workload for this course, we are glad to discuss them
with you, and our first question will be, "how much time have you spent
on this course per week, and how much time are you spending on each task
(reading, problem-solving, typesetting homeworks, etc)?" Ezra uses
<https://toggl.com/> to track his time; you should use whatever system
works best for you.
