This course is an introduction to advanced regression methods for
epidemiological research. The first part of the course will focus on
generalizations of linear regression to binary data (logistic
regression) and count data (Poisson regression). The second part of the
course will focus on time-to-event data (survival analysis). We will
look at the theoretical underpinnings of the models, but the main
emphasis will be on formulating models, fitting models to data, and
interpreting results. If time permits, we will also briefly discuss
ordinal regression.

The [schedule of class sessions and a tentative list of specific
topics](https://canvas.ucdavis.edu/courses/1077308/files/folder/Logistics)
is available on Canvas
(and reproduced on the [Schedule](schedule.qmd) page).
It will be updated regularly as the course progresses.

### Learning Objectives/Topics Overview

Upon completing the class, students are expected to be able to:

- Perform regression analysis procedures for modeling covariate‐outcome
  relationships, including:

  - Maximum likelihood inference for one homogenous sample (weeks 1-2)

  - Linear regression for continuous outcomes (weeks 2-3)

  - Logistic regression for binary outcomes (weeks 4-5)

  - Poisson regression for count outcomes (week 7)

  - Survival analysis for time‐to‐event outcomes (week 7-9)

- Appropriately apply these statistical methods to real-world data.

- Interpret the results of applying these statistical methods to data.

- Produce clearly written data analysis reports detailing:

  - Introduction

    - scientific questions

    - scientific hypotheses

  - Methods

    - study design

    - data structure

    - analytic assumptions

    - statistical methods

  - Results

    - statistical results

  - Discussion

    - interpretation of results

    - limitations of analyses

    - scientific conclusions

### Prerequisites

The required prerequisites for this class are all of the following:

- EPI 203 (Mathematical statistical inference)

- EPI 205 (Principles of epidemiology)

- STA 108 (Linear regression models)

- Instructor's consent.

Additional recommended prior coursework:

- Introduction to Statistical Programming in R: STA 015B, STA 032, STA
  035A-B, STA 141A, ENV/ECL 224, or BIS 015L
