The listed course textbooks are **optional**; we will **not** follow
them closely, and the primary content will be the lectures and
corresponding notes (<https://d-morrison.github.io/rme/> with additional
files on Canvas).

- The material in the first half of the course relies heavily on *An
  Introduction to Generalized Linear Models*, 4th ed. (2018), by Dobson,
  Annette J, and Adrian G Barnett (CRC press:
  <https://doi.org/10.1201/9781315182780>). This is a classic textbook
  for GLMs; you'll see its datasets used as examples in the R
  documentation for \`glm()\` and \`lm()\`, and the book itself provides
  R code for many of its examples. The UCLA biostatistics MS core course
  on GLMs (Biostat 200C) used this book when I was there.\
  \
  Book self-description: "The original purpose of the book was to
  present a unified theoretical and conceptual framework for statistical
  modelling in a way that was accessible to undergraduate students and
  researchers in other fields."

- Another classic textbook is Vittinghoff, Eric, David V Glidden,
  Stephen C Shiboski, and Charles E McCulloch. 2012. *Regression Methods
  in Biostatistics: Linear, Logistic, Survival, and Repeated Measures
  Models*. 2nd ed. Springer.
  <https://doi.org/10.1007/978-1-4614-1353-0>. The UCSF Epidemiology PhD
  program uses this book; its authors are/were on faculty there. The
  book provides Stata code instead of R, but I think you can find R code
  online.

- A more modern textbook for linear, logistic, and Poisson regression is
  Dunn, Peter K, Gordon K Smyth, et al. 2018. *Generalized Linear Models
  with Examples in R*. Vol. 53.
  Springer. <https://doi.org/10.1007/978-1-4419-0118-7>. I'm just
  getting started on this book, and it looks good so far.

- A more modern textbook for survival analysis models is Moore, Dirk F.
  2016. *Applied Survival Analysis Using R*. Vol. 473.
  Springer. <https://doi.org/10.1007/978-3-319-31245-3>.

- A textbook on generalized linear mixed models is Stroup, Walter W.
  *Generalized Linear Mixed Models: Modern Concepts, Methods and
  Applications* (Routledge):
  <https://www.routledge.com/Generalized-Linear-Mixed-Models-Modern-Concepts-Methods-and-Applications/Stroup/p/book/9781439815120>

The "self-learning" books by Kleinbaum and Klein are less mathematical
than this course, but provide lots of helpful practice problems:

- Logistic Regression: A Self-Learning Text (3rd ed.), Kleinbaum &
  Klein, Springer, 2010:
  <https://link.springer.com/book/10.1007/978-1-4419-1742-3>

- Survival Analysis: A Self-Learning Text (3rd ed.), Kleinbaum & Klein,
  Springer, 2012:
  <https://link.springer.com/book/10.1007/978-1-4419-6646-9>

The textbooks provide additional information and alternative
explanations of some of the course content.

See the [Canvas Reading
List](https://canvas.ucdavis.edu/courses/1077308/external_tools/10944)
page for the full up-to-date list.

Several of the texts can also be downloaded **for free** while on the
UC Davis network (or [VPN](https://library.ucdavis.edu/vpn/)), for
example using the following links:

- Logistic Regression: A Self-Learning Text (3rd ed.), Kleinbaum &
  Klein, Springer, 2010:
  <https://link.springer.com/book/10.1007/978-1-4419-1742-3>

- Survival Analysis: A Self-Learning Text (3rd ed.), Kleinbaum & Klein,
  Springer, 2012:
  <https://link.springer.com/book/10.1007/978-1-4419-6646-9>

**Soft-cover copies of Springer texts are also available for \$40**
(**cheaper than Amazon**) from the same links through Springer's MyCopy
print-on-demand service; however it may take a few weeks to ship. This
service is available for many of Springer's texts; take advantage of it
while you have an academic affiliation.

### Example Data Sets

The data sets used in the Kleinbaum & Klein textbooks are available on
the Canvas page:

- <https://canvas.ucdavis.edu/courses/1077308/files/folder/Data> (let us
  know if any are missing)
