### Coronary heart disease (WCGS) study data

::: notes
Let's use the data from the Western Collaborative Group Study (WCGS)
(@rosenman1975coronary) to explore multiple logistic regression:
:::

*From @vittinghoff2e:*

"The **Western Collaborative Group Study (WCGS)** was a large
epidemiological study designed to investigate the association between
the "type A" behavior pattern and coronary heart disease (CHD)".

---

:::{#exr-def-type-A}

What is "type A" behavior?

:::

---

:::{#sol-def-type-A}
*From Wikipedia, "Type A and Type B personality theory":*

"The hypothesis describes Type A individuals as outgoing, ambitious,
rigidly organized, highly status-conscious, impatient, anxious,
proactive, and concerned with time management....

The hypothesis describes Type B individuals as a contrast to those of
Type A. Type B personalities, by definition, are noted to live at lower
stress levels. They typically work steadily and may enjoy achievement,
although they have a greater tendency to disregard physical or mental
stress when they do not achieve."
:::

---

#### Study design

*from `?faraway::wcgs`:*

3154 healthy young men aged 39-59 from the San Francisco area were
assessed for their personality type. All were free from coronary heart
disease at the start of the research. Eight and a half years later
change in CHD status was recorded.

*Details (from `faraway::wcgs`)*

The WCGS began in 1960 with 3,524 male volunteers who were employed by
11 California companies. Subjects were 39 to 59 years old and free of
heart disease as determined by electrocardiogram. After the initial
screening, the study population dropped to 3,154 and the number of
companies to 10 because of various exclusions. The cohort comprised both
blue- and white-collar employees.

---

### Baseline data collection

socio-demographic characteristics:

-   age
-   education
-   marital status
-   income
-   occupation
-   physical and physiological including:
-   height
-   weight
-   blood pressure
-   electrocardiogram
-   corneal arcus

---

biochemical measurements:

-   cholesterol and lipoprotein fractions;
-   medical and family history and use of medications;

---

behavioral data:

-   Type A interview,
-   smoking,
-   exercise
-   alcohol use.

---

Later surveys added data on:

* anthropometry
* triglycerides
* Jenkins Activity Survey
* caffeine use

Average follow-up continued for 8.5 years with repeat examinations.


