:::{#thm-d_prob-d_logodds}

#### Derivative of probability w.r.t. log-odds

$$\derivf{\prob}{\logodds} = \pi (1-\pi)$$
:::

{{< slidebreak >}}

::: proof

By the [chain rule](math-prereqs.qmd#thm-chain-rule), @thm-d_odds-d_logodds, and @thm-deriv-invodds:

$$
\ba
\derivf{\prob}{\logodds} 
&= \green{\derivf{\odds}{\logodds}}\teal{\derivf{\prob}{\odds}}
\\
&= \green{\frac{\pi}{1-\pi}} \teal{(1-\pi)^2}
\\
&= \pi (1-\pi)
\ea
$$

Alternatively, by @thm-d_logodds-d_prob:

$$
\ba
\derivf{\prob}{\logodds} 
&= \invf{\derivf{\logodds}{\prob}}
\\
&= \invf{\frac{1}{(\prob)(1-\prob)}}
\\
&= \pi (1-\pi)
\ea
$$

:::

{{< slidebreak >}}

:::{#cor-d_pi-d_eta-var}

#### Derivative of probability w.r.t. linear predictor as a variance

If $\pi = \Pr(Y=1| \vX=\vx)$, then:

$$\derivf{\pi}{\eta} = \Varf{Y|X=x}$$
:::

{{< slidebreak >}}

::: proof

Since $Y$ is a binary (0/1) outcome
with $\Pr(Y=1|\vX=\vx) = \pi$,
the conditional distribution of $Y$ given $\vX=\vx$
is [Bernoulli](probability.qmd#def-bernoulli) with parameter $\pi$.

First, we compute $\Varf{Y|X=x}$,
using the [simplified expression for variance](probability.qmd#thm-variance),
the [expected value of the square of a Bernoulli variable](probability.qmd#exm-lotus),
and the [expectation of the Bernoulli distribution](probability.qmd#thm-bernoulli-mean),
all applied to the conditional distribution of $Y$ given $X=x$:

$$
\ba
\Varf{Y|X=x}
&= \E{Y^2|X=x} - \sqf{\E{Y|X=x}}
&& \text{(simplified expression for variance)}
\\ &= \pi - \sqf{\E{Y|X=x}}
&& \text{(expected square of a Bernoulli variable: } \E{Y^2|X=x} = \pi\text{)}
\\ &= \pi - \sqf{\pi}
&& \text{(Bernoulli mean: } \E{Y|X=x} = \pi\text{)}
\\ &= \pi(1 - \pi)
&& \text{(factor out } \pi\text{)}
\ea
$${#eq-bernoulli-cond-var}

Then, using @thm-d_prob-d_logodds and @eq-bernoulli-cond-var:

$$
\ba
\derivf{\pi}{\eta}
&= \pi(1-\pi)
&& \text{(derivative of probability w.r.t. log-odds)}
\\ &= \Varf{Y|X=x}
&& \text{(Bernoulli conditional variance, read right-to-left)}
\ea
$$

:::
