{{< include _subfiles/logistic-regression/_thm_odds-from-logodds.qmd >}}

{{< slidebreak >}}

:::{#thm-prob-from-logodds}

#### Probability as a function of log-odds

::: notes
If $\prob$ is the probability of an event $A$,
$\odds$ is the corresponding odds of $A$,
and $\logodds$ is the corresponding log-odds of $A$,
then:
:::

$$\prob = \frac{\expf{\eta}}{1+\expf{\eta}}$$

:::

{{< slidebreak >}}

::: proof
Using @thm-odds-to-prob and @lem-odds-from-logodds:

$$
\ba
\prob &= \frac{\odds}{1+\odds}
&& \text{(probability as a function of odds)}
\\ &= \frac{\expf{\logodds}}{1+\expf{\logodds}}
&& \text{(substitute } \odds = \expf{\logodds} \text{ in both places)}
\ea
$$
:::

{{< slidebreak >}}

:::{#def-expit}

#### expit, logistic, inverse-logit

The **expit function** of a log-odds $\logodds$, 
also known as the **inverse-logit function** or **logistic function**, 
is the [inverse-odds](#def-inv-odds) of the exponential of $\logodds$:

$$\expit(\logodds) \eqdef \invoddsf{\expf{\logodds}}$$

:::

{{< slidebreak >}}

:::{#thm-expit-expressions}

#### Expressions for expit function

$$
\ba
\expit(\logodds)
   &= \frac{\exp{\logodds}}{1+\exp{\logodds}}
\\ &= \frac{1}{1 + \exp{-\logodds}}
\\ &= (1 + \exp{-\logodds})^{-1}
\ea
$$
:::

{{< slidebreak >}}

::: proof
For the first expression,
apply @def-expit and then @def-inv-odds:

$$
\ba
\expit(\logodds)
&\eqdef \invoddsf{\expf{\logodds}}
&& \text{(definition of expit)}
\\ &= \frac{\expf{\logodds}}{1+\expf{\logodds}}
&& \text{(definition of inverse-odds, applied to } \odds = \expf{\logodds}\text{)}
\ea
$$

For the second and third expressions,
apply @def-expit and then @lem-invodds-simplified:

$$
\ba
\expit(\logodds)
&\eqdef \invoddsf{\expf{\logodds}}
&& \text{(definition of expit)}
\\ &= \frac{1}{1+\invf{\expf{\logodds}}}
&& \text{(simplified inverse-odds, applied to } \odds = \expf{\logodds}\text{)}
\\ &= \frac{1}{1 + \expf{-\logodds}}
&& \text{(negative-exponent rule: } \invf{\expf{x}} = \expf{-x}\text{)}
\\ &= \invf{1 + \expf{-\logodds}}
&& \text{(rewrite the reciprocal as a } -1 \text{ power)}
\ea
$$
:::

{{< slidebreak >}}

:::{#thm-expit-prob-logodds}
#### Probability via the expit function
If $\prob$ is the probability of an event $A$,
$\odds$ is the corresponding odds of $A$,
and $\logodds$ is the corresponding log-odds of $A$,
then:

$$\prob = \expitf{\logodds}$$

:::

{{< slidebreak >}}

::: proof

Using @thm-prob-from-logodds and @thm-expit-expressions:

$$
\ba
\prob &= \frac{\expf{\logodds}}{1+\expf{\logodds}}
&& \text{(probability as a function of log-odds)}
\\ &= \expitf{\logodds}
&& \text{(first expression for expit, read right-to-left)}
\ea
$$
:::

{{< slidebreak >}}

@fig-expit-plot graphs the expit function.

:::{#fig-expit-plot}

```{r}
#| code-fold: true
expit <- function(eta) {
  exp(eta) / (1 + exp(eta))
}
library(ggplot2)
expit_plot <-
  ggplot() +
  geom_function(
    fun = expit,
    arrow = arrow(ends = "both")
  ) +
  xlim(-8, 8) +
  ylim(0, 1) +
  ylab(expression(expit(eta))) +
  xlab(expression(eta)) +
  theme_bw()
print(expit_plot)
```

The expit function

:::

{{< slidebreak >}}

{{< include _subfiles/logistic-regression/_sec_logit-expit_inverse.qmd >}}
