:::{#def-logodds}
#### log-odds
::: notes
If $\omega$ is the odds of an event $A$,
then the **log-odds** of $A$,
which we will represent by $\logodds$ ("eta"),
is the natural logarithm of the odds of $A$:
:::

$$\logodds \eqdef \logf{\omega}$${#eq-def-logodds}

:::

{{< slidebreak >}}

:::{#thm-logodds-pi}

#### Log-odds as a function of probability

If $\prob$ is the probability of an event $A$,
$\odds$ is the corresponding odds of $A$,
and $\eta$ is the corresponding log-odds of $A$,
then:

$$\logodds = \logf{\frac{\prob}{1-\prob}}$${#eq-logodds-from-prob}

:::

{{< slidebreak >}}

::: proof
Using @def-logodds and @thm-prob-to-odds:

$$
\ba
\logodds &\eqdef \logf{\odds}
&& \text{(definition of log-odds)}
\\ &= \logf{\frac{\prob}{1-\prob}}
&& \text{(odds as a function of probability)}
\ea
$$
:::

{{< slidebreak >}}

:::{#def-logit-fn}

#### logit function

::: notes
The **logit function**  of a probability $\prob$ is
the natural logarithm of the [odds function](#def-odds-fn) of $\prob$:
:::

$$\logit(\prob) \eqdef \logf{\oddsf{\prob}}$$

::: notes

The **logit function** is a [composite function](https://en.wikipedia.org/wiki/Function_composition).

:::

:::

{{< slidebreak >}}

:::{#exr-prove-eq-logit}

#### Compose the logit function

Mathematically expand the definition of the logit function.

:::

{{< slidebreak >}}

:::{#sol-prove-eq-logit}
#### Compose the logit function

:::{#thm-logit-function}
#### Expanded expression for logit
$$\logit(\prob) = \logf{\frac{\prob}{1-\prob}}$${#eq-logit}

:::

::: proof
Using @def-logit-fn and @def-odds-fn:

$$
\ba
\logit(\prob)
&\eqdef \logf{\oddsf{\prob}}
&& \text{(definition of logit)}
\\ &= \logf{\frac{\prob}{1-\prob}}
&& \text{(definition of the odds function)}
\ea
$$
:::

:::

{{< slidebreak >}}

:::{#cor-logodds-logit}
#### Log-odds via the logit function
If $\prob$ is the probability of an event $A$
and $\logodds$ is the corresponding log-odds of $A$,
then:

$$\logodds = \logitf{\prob}$$

:::

{{< slidebreak >}}

::: proof

Using @thm-logodds-pi and @thm-logit-function:

$$
\ba
\logodds &= \logf{\frac{\prob}{1-\prob}}
&& \text{(log-odds as a function of probability)}
\\ &= \logitf{\prob}
&& \text{(expanded expression for logit, read right-to-left)}
\ea
$$

:::

{{< slidebreak >}}

:::{#exm-logit-numeric}

#### Log-odds of an event with probability 0.75

Suppose the probability of an event $A$ is $\prob = 0.75$.
Then, by @thm-prob-to-odds,
the corresponding odds of $A$ are
$\odds = \frac{0.75}{1-0.75} = \frac{0.75}{0.25} = 3$,
and by @cor-logodds-logit and @thm-logit-function,
the corresponding log-odds of $A$ are:

$$
\ba
\logodds = \logitf{0.75}
&= \logf{\frac{0.75}{1-0.75}}
&& \text{(expanded expression for logit)}
\\ &= \logf{\frac{0.75}{0.25}}
&& \text{(subtract: } 1 - 0.75 = 0.25\text{)}
\\ &= \logf{3}
&& \text{(divide: } 0.75 / 0.25 = 3\text{)}
\\ &\approx 1.0986
&& \text{(evaluate the natural logarithm)}
\ea
$$

:::

{{< slidebreak >}}

::: notes
@fig-logit shows the shape of the $\logit()$ function.
:::

:::{#fig-logit}

```{r}
#| code-fold: true

odds <- function(pi) pi / (1 - pi)

logit <- function(p) log(odds(p))

library(ggplot2)
logit_plot <-
  ggplot() +
  geom_function(
    fun = logit,
    arrow = arrow(ends = "both")
  ) +
  xlim(.001, .999) +
  ylab("logit(p)") +
  xlab("p") +
  theme_bw()
print(logit_plot)
```

The logit function

:::

