
::: notes
@tbl-oc-mi simulates a follow-up study in which two populations were followed and the number of MI’s was observed.
The risks are $P(MI|OC)$ and $P(MI|\neg OC)$ and we can estimate these risks from the data.

But suppose we had a case-control study in which we had 100 women with MI and selected a comparison group of 100 women without MI (matched as groups on age, etc.).
Then MI is not random, and we cannot compute P(MI|OC) and we cannot compute the risk ratio.
However, the odds ratio can be computed.
:::

{{< slidebreak >}}

:::{#def-disease-OR}

#### Disease odds ratio

For a disease $D$ and an exposure $E$,
the **disease odds ratio** is
the odds of disease in the exposed group
divided by the odds of disease in the unexposed group:

$$\ror(D|E) \eqdef \frac{\odds(D|E)}{\odds(D|\neg E)}$$

:::

::: notes
In a case-control study,
disease status is not random,
so we cannot validly compute or use the separate parts
$\odds(D|E)$ and $\odds(D|\neg E)$ of the disease odds ratio.
:::

{{< slidebreak >}}

:::{#def-exposure-OR}

#### Exposure odds ratio

For a disease $D$ and an exposure $E$,
the **exposure odds ratio** is
the odds of exposure in the diseased group
divided by the odds of exposure in the non-diseased group:

$$\ror(E|D) \eqdef \frac{\odds(E|D)}{\odds(E|\neg D)}$$

:::

::: notes
We can still validly compute and use the exposure odds ratio,
because exposure can be treated as random.
:::

{{< slidebreak >}}

:::{#exm-exposure-OR-oc-mi}

#### Exposure odds ratio in the OC-MI study

For the OC-MI study,
the estimated exposure odds ratio is:

$$
\hror(OC|MI) =
\frac{\hodds(OC|MI)}{\hodds(OC|\neg MI)}
$$

::: notes
And these two odds ratios, $\hror(MI|OC)$ and $\hror(OC|MI)$,
are mathematically equivalent, as we saw in @sec-OR-props:
:::

$$\hror(MI|OC) = \hror(OC|MI)$$

:::

{{< slidebreak >}}

:::{#exr-or-rev}

Calculate the odds ratio of MI with respect to OC use,
assuming that @tbl-oc-mi comes from a case-control study.
Confirm that the result is the same as in @exm-OR.

:::

{{< slidebreak >}}

:::: {.solution}

:::{#tbl-oc-mi2}

```{r}
tbl_oc_mi |> pander::pander()
```

Simulated data from study of oral contraceptive use and heart attack risk

:::

* $\odds(OC|MI) = P(OC|MI)/(1 - P(OC|MI)) = \frac{13}{7} = `r 13/7`$

* $\odds(OC|\neg MI) = P(OC|\neg MI)/(1 - P(OC|\neg MI)) = \frac{4987}{9993} = `r 4987/9993`$

* $\ror(OC|MI) = \frac{\odds(OC|MI)}{\odds(OC|\neg MI)} = \frac{13/7}{4987/9993} = `r (13/7)/(4987/9993)`$

::: notes
This odds-ratio estimate is the same one we calculated in @exm-OR.
:::

::::
