project:
  output-dir: _slides
  render:
    - intro-to-GLMs.qmd
    - intro-MLEs.qmd
    - glms.qmd
    - Linear-models-overview.qmd
    - logistic-regression.qmd
    - count-regression.qmd
    - time-to-event-models.qmd
    - intro-to-survival-analysis.qmd
    - proportional-hazards-models.qmd
    - parametric-survival-models.qmd
    - probability.qmd
    - estimation.qmd
    - intro-MLEs.qmd

format:
  revealjs:
    bibliography: references.bib
    # reference-location: margin
    citations-hover: true
    theme: dark
    embed-resources: true
    fig-cap-location: top
    html-math-method: mathjax
    smaller: false
    number-sections: true
    progress: true
    incremental: false
    df-print: paged
    number-depth: 2
    slide-number: true
    shift-heading-level-by: -1
    slide-level: 2
    scrollable: true
    echo: true
    margin: 0
    code-fold: true
    code-link: true
    code-summary: "[R code]"
    # code-overflow: scroll
    auto-stretch: true
    # out-width: "50%"
    fig-height: 5
    fig-width: 7
    # chalkboard: true
include-in-header:
  text: |
    <style>
      .custom-small table {
        font-size: .5em
      }
    </style>
execute:
  warning: false
  message: false
  cache: false
  freeze: auto  # re-render only when source changes
knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
