---
title: "Linear (Gaussian) Models"
format:
  html: default
  revealjs:
    output-file: Linear-models-overview-slides.html
  pdf:
    output-file: Linear-models-overview-handout.pdf
  docx:
    output-file: Linear-models-overview-handout.docx

---


{{< include shared-config.qmd >}}

```{r}
include_reference_lines <- FALSE
```

---

:::{.callout-note}
This content is adapted from:

- @dobson4e, Chapters 2-6
- @dunn2018generalized, Chapters 2-3
- @vittinghoff2e, Chapter 4

There are numerous textbooks specifically for linear regression, including:

- @kutner2005applied: used for UCLA Biostatistics MS level linear models class
- @chatterjee2015regression: used for Stanford MS-level linear models class
- @seber2012linear: used for UCLA Biostatistics PhD level linear models class and UC Davis STA 108.
- @kleinbaum2014applied: same first author as @kleinbaum2010logistic and @kleinbaum2012survival
- *Linear Models with R* [@Faraway2025-io]
- *Applied Linear Regression* by Sanford Weisberg [@weisberg2005applied]

For more recommendations, see the discussion on [Reddit](https://www.reddit.com/r/statistics/comments/qwgctl/q_books_on_applied_linear_modelsregression_for/).

- see also <https://web.stanford.edu/class/stats191>
^[the current version of the first regression course I ever took]

:::

# Overview

{{< include _subfiles/Linear-models-overview/_sec_linreg_overview.qmd >}}

# Understanding Gaussian Linear Regression Models {#sec-understand-LMs}

{{< include _subfiles/Linear-models-overview/_sec_linreg_understanding.qmd >}}

# Fitting linear models {#sec-est-LMs}

{{< include _subfiles/Linear-models-overview/_sec_linreg_est.qmd >}}

# Assessing model fit {#sec-assess-LMs}

{{< include _subfiles/Linear-models-overview/_sec_linreg_assess.qmd >}}

# Inference about Gaussian Linear Regression Models {#sec-infer-LMs}

{{< include _subfiles/Linear-models-overview/_sec_linreg_inference.qmd >}}

# Multiple linear regression: the HERS study {#sec-multiple-lm-hers}

{{< include _subfiles/Linear-models-overview/_sec_hers_worked_example.qmd >}}

# End-of-chapter exercises

{{< include _subfiles/Linear-models-overview/_sec_linreg_end_of_chapter_exercises.qmd >}}

# Exercises {.unnumbered}

{{< include _subfiles/Linear-models-overview/_exr-prac-linreg-lik.qmd >}}

---

{{< include _subfiles/Linear-models-overview/_exr-prac-linreg-score.qmd >}}

---

{{< include _subfiles/Linear-models-overview/_exr-prac-slr-closed-form.qmd >}}

---

{{< include _subfiles/Linear-models-overview/_exr-prac-coef-interp.qmd >}}

---

{{< include _subfiles/Linear-models-overview/_exr-prac-r2.qmd >}}

# References {.unnumbered}

::: {#refs}
:::
