---
title: "Models for Binary Outcomes"
subtitle: "Logistic regression and variations"
format:
  html: default
  revealjs:
    output-file: logistic-regression-slides.html
  pdf:
    output-file: logistic-regression-handout.pdf
    df-print: tibble
  docx:
    output-file: logistic-regression-handout.docx

---


{{< include shared-config.qmd >}}

```{r}
options(digits = 6)
```


## Acknowledgements {.unnumbered}

This content is adapted from:

-   @dobson4e, Chapter 7
-   @vittinghoff2e, Chapter 5
- [David Rocke](https://dmrocke.ucdavis.edu/)'s materials from the [2021 edition of Epi 204](https://dmrocke.ucdavis.edu/Class/EPI204-Spring-2021/EPI204-Spring-2021.html)
-   @NahhasIRMPHR [Chapter 6](https://www.bookdown.org/rwnahhas/RMPH/blr.html)

# Introduction

{{< include _subfiles/logistic-regression/_sec_overview_bernoulli_models.qmd >}}

{{< include _subfiles/logistic-regression/_sec_intro_bernoulli_models.qmd >}}

# Introduction to logistic regression

{{< include _subfiles/logistic-regression/_sec_one_cov_logistic.qmd >}}

# Derivatives of logistic regression functions

{{< include _subfiles/logistic-regression/_sec_logistic-reg-derivatives.qmd >}}

# Understanding logistic regression models

{{< include _subfiles/logistic-regression/_sec_logistic_slope_mean.qmd >}}

{{< slidebreak >}}

{{< include _subfiles/logistic-regression/_sec_derivs_MLE.qmd >}}

{{< slidebreak >}}

{{< include _subfiles/logistic-regression/_sec_OR_logistic.qmd >}}

# Estimating logistic regression models

{{< include _subfiles/logistic-regression/_sec_logistic-fitting.qmd >}}

# Inference for logistic regression models

## Inference for individual predictor coefficients

### Wald tests and confidence intervals

{{< include _subfiles/logistic-regression/_sec_logistic_wald.qmd >}}

## Inference for predicted probabilities

{{< include _subfiles/logistic-regression/_sec_logistic_pred_inference.qmd >}}

## Inference for odds ratios {#sec-or-inference}

{{< include _subfiles/logistic-regression/_sec_OR_inference.qmd >}}

# Multiple logistic regression

{{< include _subfiles/logistic-regression/_sec_exm_wcgs.qmd >}}

# Model comparisons for logistic models {#sec-gof}

{{< include _subfiles/logistic-regression/_sec_logistic_gof.qmd >}}

# Residual-based diagnostics

{{< include _subfiles/logistic-regression/_sec_logistic_dx.qmd >}}

# Alternatives to reporting odds ratios

{{< include _subfiles/logistic-regression/_sec-OR-alternatives.qmd >}}

# Further reading

- @hosmer2013applied is a classic textbook on logistic regression

# Exercises {.unnumbered}

{{< include _subfiles/logistic-regression/_exr-link-function-choice.qmd >}}

# Summary of definitions and results {.unnumbered}

{{< include _subfiles/logistic-regression/_sec_logistic_summary.qmd >}}

# References {.unnumbered}

::: {#refs}
:::
