::: callout-warning
Epi 202, Epi 203, and Sta 108 are prerequisites for this course. 
If you haven't passed one of these courses, talk to me ASAP.
:::

### Epi 202: probability models

- Probability distributions
    -   binomial
    -   Poisson
    -   Gaussian
    -   exponential

---

- Characteristics of probability distributions
    - Mean, median, mode, quantiles
    - Variance, standard deviation, overdispersion

---

- Characteristics of samples
    - independence, dependence, covariance, correlation
    - ranks, order statistics
    - identical vs nonidentical distribution (homogeneity vs heterogeneity)
    - Laws of Large Numbers
    - Central Limit Theorem for the mean of an iid sample

### Epi 203: inference for one or several homogenous populations {.smaller}

* the maximum likelihood inference framework:
    + likelihood functions
    + log-likelihood functions
    + score functions
    + estimating equations
    + information matrices
    + point estimates
    + standard errors
    + confidence intervals
    + hypothesis tests
    + p-values

---

* Hypothesis tests for one, two, and >2 groups:
    + t-tests/ANOVA for Gaussian models
    + chi-square tests for binomial and Poisson models
    + nonparametric tests:
        - Wilcoxon signed-rank test for matched pairs
        - Mann–Whitney/Kruskal-Wallis rank sum test 
        for $\geq 2$ independent samples
        - Fisher's exact test for contingency tables
        - Cochran–Mantel–Haenszel-Cox log-rank test

---

For all of the quantities above, 
and especially for confidence intervals and p-values, 
you should know how **both**:

- how to compute them
- how to interpret them

---

### Stat 108: linear regression models {.smaller}

* building models for Gaussian outcomes
    + multiple predictors
    + interactions
* regression diagnostics
* fundamentals of R programming; e.g.:     
    + @r4ds
    + @dalgaardintroductory
* [RMarkdown or Quarto for formatting homework](https://r4ds.hadley.nz/quarto)
    + LaTeX for writing math in RMarkdown/Quarto
