---
title: "Time to Event Models"
format:
  html: default
  revealjs:
    output-file: time-to-event-models-slides.html
  pdf:
    output-file: time-to-event-models-handout.pdf
  docx:
    output-file: time-to-event-models-handout.docx

---

In many health sciences applications, binary outcomes are *incompletely observed*.
For example, if we are studying whether cancer patients experience a relapse after an initial remission,
we may not be able to follow patients to the end of their lives;
instead, we may only know whether each patient has relapsed before the end of the study.
If a patient has not relapsed by that point,
we might not know if they will relapse at some other date
or if they will stay cancer-free for the rest of their lives.
^[Binary outcomes are typically defined *for a specific time-point*.
It is important to clearly define whether we are interested in outcome status at end of study, at end of life, or at some other time.]
Their recurrence status at end-of-life is *missing data*.
If some study participants withdraw from a study before the scheduled end date, additional missing data arise.
Standard logistic regression cannot handle such right-censored data directly without introducing bias.

However, these outcome observations are not *entirely* missing.
We know that those patients stayed relapse-free *at least* until the time point when they were last observed.
If we also know the *time-to-event* for participants who experienced events while under study,
we can analyze the *time-to-event-or-study-exit* alongside an event indicator using *survival analysis*.
The survival analysis framework provides the foundation for the topics covered in this module.

