---
title: "Summary of Regression Modeling Concepts"
format:
  html: default
  revealjs:
    output-file: top-ten-concepts-slides.html
  pdf:
    output-file: top-ten-concepts-handout.pdf
  docx:
    output-file: top-ten-concepts-handout.docx

---

{{< include shared-config.qmd >}}

# We use different probability models for different data types

* Binary outcomes: Bernoulli models
* Event rate outcomes: Poisson/Negative binomial models
* Time-to-event outcomes: Survival models
* Catch-all: Gaussian models

# We use different link functions to connect these models with covariates

* Bernoulli models: logit link
* Count models: log link + offset
* Survival models: log link
* Gaussian models: identity link

@fig-model-diagrams shows how the various models we have studied
have analogous structures:
each row uses model-specific transformations to connect
the modeled quantity
to a linear predictor
$\lincomp(\vx) = \dprodf{\vx}{\vb} + \lincomp_0$.

:::{#fig-model-diagrams}

{{< include _subfiles/top-ten-concepts/_fig-model-diagrams-content.qmd >}}

Parallel structures of GLMs and survival models.
Each row shows the transformation chain from the modeled quantity
to the linear predictor
$\lincomp(\vx) = \dprodf{\vx}{\vb} + \lincomp_0$,
where $\lincomp_0$ is the intercept term for each model
($\lincomp_0 = \mu(0)$ for linear,
$\lincomp_0 = \logodds(0)$ for logistic,
$\lincomp_0 = \logf{\rate(0)}$ for Poisson,
and $\lincomp_0(t) = \loghaz_0(t)$ for Cox PH).

:::

# We use maximum likelihood estimation to fit models to data

* likelihood
* log-likelihood
* score function
* hessian

# We use asymptotic normality of MLEs to quantify uncertainty about models

* observed information matrix
* expected information matrix
* standard error
* confidence intervals
* p-values

# We use (log) likelihood ratios to compare models

Sometimes we adjust these comparisons for model size (AIC, BIC)

# References {.unnumbered}

::: {#refs}
:::
