name: Quarto Preview Build Companion

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, closed]
    paths-ignore:
      - 'man/**'
      - 'pkgdown/**'
      - 'vignettes/**'
      - '_extensions/**'
      - '_quarto*.yml'
      - '.github/workflows/preview.yml'
      - '*.qmd'
      - 'chapters/**/*.qmd'
      - '_subfiles/**'
      - '*.scss'
      - 'latex-macros'
      - 'references.bib'
      - 'renv.lock'
      - 'DESCRIPTION'

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/noop.yml # zizmor: ignore[self-repository]
