name: Check junk files

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - dev

jobs:
  check-junk-files:
    permissions:
      contents: read
    uses: Morrison-Lab/gha/.github/workflows/check-junk-files.yml@v2
    with:
      patterns: ".DS_Store, ._*, .Rproj.user, .Rhistory, .RData, .httr-oauth, .quarto, Thumbs.db, desktop.ini, *-tmp.yml"
