name: Quarto Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - uses: r-lib/actions/setup-r@HEAD
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@HEAD
        with:
          needs: |
            connect
            website
          extra-packages: |
            local::.
            any::pkgdown

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: list files
        shell: bash
        run: |
          ls _book/
          ls .
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@main
        with:
          source-dir: _book/

