on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@HEAD

      - name: list files
        shell: bash
        run: |
          ls
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@HEAD

      - uses: r-lib/actions/setup-r@HEAD
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@HEAD
        with:
          needs: |
            connect
            website
          extra-packages: |
            local::.
            any::pkgdown

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@HEAD
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
